export interface AbilityBattleDesc {
  en: string;
  fr: string;
  es: string;
  de: string;
  it: string;
  ja: string;
  ko: string;
}

export const ABILITY_BATTLE_DESCRIPTIONS: Record<string, AbilityBattleDesc> = {
  intimidate: {
    en: "Lowers all opponents' Attack by 1 stage on switch-in. Excellent for physical walling and disrupting setup sweepers.",
    fr: "Baisse l'Attaque des adversaires d'1 cran à l'entrée. Excellent pour le mur physique et perturber les setup sweeper.",
    es: "Reduce el Ataque de los rivales 1 nivel al entrar. Excelente para defender físicamente y frenar setup sweepers.",
    de: "Senkt den Angriff aller Gegner um 1 Stufe beim Wechsel. Ideal als physische Wand und gegen Setup-Sweeper.",
    it: "Abbassa l'Attacco degli avversari di 1 livello all'ingresso. Ottimo come wall fisico e contro i setup sweeper.",
    ja: "出場時に相手の攻撃を1段階下げる。物理受けや積み技対策に優秀。",
    ko: "등장 시 상대의 공격을 1단계 낮춘다. 물리受け와 쌓기 기술 대책에 우수.",
  },
  levitate: {
    en: "Immune to Ground-type moves. Removes a major weakness for many Pokémon, providing key defensive utility.",
    fr: "Immunisé contre les capacités Sol. Élimine une faiblesse majeure, offrant une utilité défensive clé.",
    es: "Inmune a movimientos de tipo Tierra. Elimina una debilidad clave, proporcionando gran utilidad defensiva.",
    de: "Immun gegen Boden-Attacken. Beseitigt eine große Schwäche und bietet wichtige defensive Nutzung.",
    it: "Immune alle mosse di tipo Terra. Rimuove una debolezza importante, offrendo grande utilità difensiva.",
    ja: "地面タイプ技を無効化。多くのポケモンの弱点を消し、防御面で重要な役割を果たす。",
    ko: "땅 타입 기술을 무효화. 많은 포켓몬의 약점을 없애고 방어면에서 중요한 역할.",
  },
  "magic-guard": {
    en: "Takes damage only from direct attacks. Immune to weather, status, entry hazards, and recoil — perfect for setup sweepers.",
    fr: "Ne subit que les dégâts directs. Immunisé contre la météo, les statuts, les pièges et le recoil — parfait pour les setup sweeper.",
    es: "Solo recibe daño de ataques directos. Inmune a clima, estados, hazards y recoil — perfecto para setup sweepers.",
    de: "Nimmt nur Schaden durch direkte Angriffe. Immun gegen Wetter, Status, Entry Hazards und Recoil — perfekt für Setup-Sweeper.",
    it: "Subisce danni solo da attacchi diretti. immune a meteo, stati, entry hazard e recoil — perfetto per i setup sweeper.",
    ja: "直接攻撃のみダメージを受ける。天候、状態異常、ステルスロック、反動ダメージを無効化。積み技エースに最適。",
    ko: "직접 공격으로만 데미지를 받음. 날씨, 상태이상, 스텔스록, 반동 데미지를 무효화. 쌓기 에이스에 최적.",
  },
  "speed-boost": {
    en: "Raises Speed by 1 stage every turn. Turns slow Pokémon into late-game sweepers after a few boosts.",
    fr: "Augmente la Vitesse d'1 cran chaque tour. Transforme les Pokémon lents en sweepers en late-game après quelques boosts.",
    es: "Aumenta la Velocidad 1 nivel cada turno. Convierte Pokémon lentos en sweepers de late-game tras unos pocos turnos.",
    de: "Erhöht die Initiative jede Runde um 1 Stufe. Macht langsame Pokémon nach einigen Steigerungen zu Sweepern.",
    it: "Aumenta la Velocità di 1 livello ogni turno. Trasforma Pokémon lenti in sweeper nel late-game dopo qualche boost.",
    ja: "毎ターン素早さが1段階上がる。数ターン後には遅いポケモンがエースに変わる。",
    ko: "매 턴 스피드가 1단계 상승. 몇 턴 후 느린 포켓몬이 에이스로 변신.",
  },
  "huge-power": {
    en: "Doubles Attack stat. Combined with Swords Dance or Belly Drum, this ability can reach devastating damage output.",
    fr: "Double l'Attaque. Combiné avec Danse-Lames ou Cognobidon, cette capacité peut atteindre des dégâts dévastateurs.",
    es: "Duplica el Ataque. Combinado con Danza Espada o Danza Lluvia, puede alcanzar un daño devastador.",
    de: "Verdoppelt den Angriff. Kombiniert mit Schwerttanz oder Delegator erreicht es verheerenden Schaden.",
    it: "Raddoppia l'Attacco. Combinato con Danzaspada o Centriperno, può raggiungere danni devastanti.",
    ja: "攻撃力が2倍になる。剣の舞や腹太鼓と組み合わせると壊滅的なダメージを出せる。",
    ko: "공격력이 2배. 검의 춤이나 배북과 조합하면 치명적인 데미지를 낼 수 있음.",
  },
  "pure-power": {
    en: "Doubles Attack stat. Same as Huge Power — turns any Pokémon into a devastating physical attacker.",
    fr: "Double l'Attaque. Comme Coloforce — transforme n'importe quel Pokémon en attaquant physique dévastateur.",
    es: "Duplica el Ataque. Igual que Potencia — convierte cualquier Pokémon en un atacante físico devastador.",
    de: "Verdoppelt den Angriff. Wie Kraftkoloss — macht jedes Pokémon zu einem verheerenden physischen Angreifer.",
    it: "Raddoppia l'Attacco. Come Macroforza — trasforma qualsiasi Pokémon in un attaccante fisico devastante.",
    ja: "攻撃力が2倍になる。ヨガパワーと同じ — どんなポケモンも壊滅的な物理アタッカーに変える。",
    ko: "공격력이 2배. 요가파워와 동일 — 어떤 포켓몬도 치명적인 물리 공격자로 만듦.",
  },
  "multiscale": {
    en: "Halves damage taken when at full HP. Provides incredible setup opportunities — forces opponents to break the Multiscale first.",
    fr: "Réduit de moitié les dégâts subis à pleine PV. Offre des opportunités de setup incroyables — force l'adversaire à casser l'Écran Fumée d'abord.",
    es: "Reduce a la mitad el daño recibido a HP completo. Ofrece increíbles oportunidades de setup — obliga al rival a romper Multiescala primero.",
    de: "Halbiert erlittenen Schaden bei vollen KP. Bietet unglaubliche Setup-Möglichkeiten — zwingt Gegner, die Multiscale zuerst zu brechen.",
    it: "Dimezza i danni subiti a HP pieni. Offre incredibili opportunità di setup — obbliga l'avversario a rompere Multiscale prima.",
    ja: "満HP時に受けるダメージを半分にする。圧倒的な積み技機会を提供 — 相手はまずマルチスケイルを壊す必要がある。",
    ko: "풀HP 시 받는 데미지 절반. 압도적인 쌓기 기회 제공 — 상대는 먼저 멀티스케일을 깨야 함.",
  },
  "magic-bounce": {
    en: "Reflects status moves back at the user. Bounces back Taunt, Stealth Rock, Toxic, and other setup moves — excellent support ability.",
    fr: "Renvoie les capacités de statut à l'utilisateur. Renvoie Provoc, Piège de Roc, Toxic et autres — excellent talent de support.",
    es: "Refleja movimientos de estado al usuario. Rebota Provocación, Rocas, Tóxico y otros — excelente habilidad de soporte.",
    de: "Reflektiert Status-Attacken zum Anwender zurück. Wehrt Spotter, Tarnsteine, Toxin und andere ab — hervorragende Support-Fähigkeit.",
    it: "Riflette le mosse di stato al mittente. Rimbalza Provocazione, Levitoroccia, Tossina e altre — ottima abilità di supporto.",
    ja: "変化技を跳ね返す。挑発、ステルスロック、どくどくなどを返す — 優秀なサポート特性。",
    ko: "변화 기술을 되돌림. 도발, 스텔스록, 맹독 등을 반사 — 우수한 서포트 특성.",
  },
  "adaptability": {
    en: "Increases STAB multiplier from 1.5× to 2×. Makes same-type attacks significantly stronger — excellent for offensive Pokémon.",
    fr: "Augmente le multiplicateur STAB de 1,5× à 2×. Rend les capacités du même type nettement plus fortes — excellent pour les Pokémon offensifs.",
    es: "Aumenta el multiplicador STAB de 1.5× a 2×. Hace que los ataques del mismo tipo sean mucho más fuertes — excelente para Pokémon ofensivos.",
    de: "Erhöht den STAB-Multiplikator von 1,5× auf 2×. Macht Typ-Attacken deutlich stärker — hervorragend für offensive Pokémon.",
    it: "Aumenta il moltiplicatore STAB da 1.5× a 2×. Rende le mosse dello stesso tipo molto più forti — ottimo per Pokémon offensivi.",
    ja: "タイプ一致補正を1.5倍から2倍に上げる。同じタイプの技が大幅に強化 — 攻撃的なポケモンに最適。",
    ko: "타입 일치 보정을 1.5배에서 2배로 증가. 같은 타입 기술이 크게 강화 — 공격적인 포켓몬에 최적.",
  },
  "regenerator": {
    en: "Restores 33% HP on switch-out. Enables excellent pivot play — switch in and out repeatedly without losing momentum.",
    fr: "Rend 33% des PV en quittant le combat. Permet un excellent pivot — entrez et sortez sans perdre d'élan.",
    es: "Restaura 33% de HP al cambiar. Permite un excelente pivot — entra y sale repetidamente sin perder momentum.",
    de: "Stellt 33% KP beim Wechsel wieder her. Ermöglicht exzellentes Pivot-Spiel — wiederholt rein und raus ohne Momentumverlust.",
    it: "Ripristina il 33% degli HP allo switch. Permette un eccellente pivot — entra ed esci ripetutamente senza perdere slancio.",
    ja: "交代時にHPを33%回復。優秀なピボットプレイが可能 — 勢いを保ったまま繰り返し出入りできる。",
    ko: "교대 시 HP 33% 회복. 우수한 피벗 플레이 가능 — 모멘텀을 유지하며 반복적으로 출입.",
  },
  "unaware": {
    en: "Ignores opponent's stat changes when attacking or defending. Hard counters setup sweepers that have boosted their stats.",
    fr: "Ignore les changements de stats de l'adversaire en attaque et défense. Contre les setup sweepers qui ont boosté leurs stats.",
    es: "Ignora los cambios de stats del rival al atacar o defender. Counter duro contra setup sweepers que han boosteado.",
    de: "Ignoriert gegnerische Stat-Änderungen bei Angriff und Verteidigung. Harter Counter gegen Setup-Sweeper mit Boosts.",
    it: "Ignora i cambiamenti di stats dell'avversario in attacco e difesa. Counter duro contro setup sweeper con boost.",
    ja: "攻撃・防御時に相手のランク補正を無視する。積み技エースに対する強力なカウンター。",
    ko: "공격·방어 시 상대의 랭크 보정을 무시. 쌓기 에이스에 대한 강력한 카운터.",
  },
  "prankster": {
    en: "Gives +1 priority to status moves. Allows you to set up screens, status conditions, or Taunt before opponents can act.",
    fr: "Donne +1 de priorité aux capacités de statut. Permet de placer les murs, statuts ou Provoc avant que l'adversaire n'agisse.",
    es: "Da +1 de prioridad a movimientos de estado. Permite colocar pantallas, estados o Provocación antes de que el rival actúe.",
    de: "Gibt Status-Attacken +1 Priorität. Ermöglicht Lichtschild, Status oder Spotter bevor der Gegner handeln kann.",
    it: "Dà +1 priorità alle mosse di stato. Permette di piazzare schermi, stati o Provocazione prima che l'avversario agisca.",
    ja: "変化技の優先度+1。壁貼り、状態異常、挑発を相手より先に出せる。",
    ko: "변화 기술 우선도+1. 벽 치기, 상태이상, 도발을 상대보다 먼저 사용.",
  },
  "storm-drain": {
    en: "Draws in Water-type moves, boosting Special Attack. Immune to Water and provides a free Special Attack boost — great defensive ability.",
    fr: "Attire les capacités Eau, boostant l'Attaque Spéciale. Immunisé contre l'Eau et offre un boost gratuit d'Attaque Spéciale.",
    es: "Atrae movimientos de tipo Agua, aumentando el Ataque Especial. Inmune al Agua y da un boost gratis — gran habilidad defensiva.",
    de: "Zieht Wasser-Attacken an und steigert den Spezial-Angriff. Immun gegen Wasser und gibt kostenlosen Boost — großartige defensive Fähigkeit.",
    it: "Attira le mosse di tipo Acqua, aumentando l'Attacco Speciale. immune all'Acqua e dà un boost gratis — grande abilità difensiva.",
    ja: "水タイプ技を引き寄せ、特攻を上げる。水技を無効化しつつ特攻を無料でブースト — 優秀な防御特性。",
    ko: "물 타입 기술을 끌어당겨 특공 상승. 물 기술 무효화 + 무료 특공 부스트 — 우수한 방어 특성.",
  },
  "lightning-rod": {
    en: "Draws in Electric-type moves, boosting Special Attack. Immune to Electric and provides a free Special Attack boost.",
    fr: "Attire les capacités Électrik, boostant l'Attaque Spéciale. Immunisé contre l'Électrik et offre un boost gratuit.",
    es: "Atrae movimientos de tipo Eléctrico, aumentando el Ataque Especial. Inmune al Eléctrico y da un boost gratis.",
    de: "Zieht Elektro-Attacken an und steigert den Spezial-Angriff. Immun gegen Elektro und gibt kostenlosen Boost.",
    it: "Attira le mosse di tipo Elettro, aumentando l'Attacco Speciale. immune all'Elettro e dà un boost gratis.",
    ja: "電気タイプ技を引き寄せ、特攻を上げる。電気技を無効化しつつ特攻を無料でブースト。",
    ko: "전기 타입 기술을 끌어당겨 특공 상승. 전기 기술 무효화 + 무료 특공 부스트.",
  },
  "flash-fire": {
    en: "Boosts Fire-type moves by 50% when hit by a Fire move. Immune to Fire and provides a free damage boost — great for Fire-types.",
    fr: "Booste les capacités Feu de 50% quand touché par une capacité Feu. Immunisé contre le Feu et offre un boost de dégâts gratuit.",
    es: "Potencia movimientos de tipo Fuego 50% al ser golpeado por Fuego. Inmune al Fuego y da un boost de daño gratis.",
    de: "Steigert Feuer-Attacken um 50% bei Treffer durch Feuer. Immun gegen Feuer und gibt kostenlosen Schadensboost.",
    it: "Potenzia le mosse di tipo Fuoco del 50% quando colpito da Fuoco. immune al Fuoco e dà un boost di danno gratis.",
    ja: "炎技を受けると炎タイプの技が50%強化。炎技を無効化しつつダメージブースト — 炎タイプに最適。",
    ko: "불꽃 기술 맞으면 불꽃 타입 기술 50% 강화. 불꽃 기술 무효화 + 데미지 부스트 — 불꽃 타입에 최적.",
  },
  "water-absorb": {
    en: "Restores 25% HP when hit by a Water move. Immune to Water and provides free healing — excellent for defensive pivots.",
    fr: "Rend 25% des PV quand touché par une capacité Eau. Immunisé contre l'Eau et offre des soins gratuits — excellent pour les pivots défensifs.",
    es: "Restaura 25% de HP al ser golpeado por Agua. Inmune al Agua y da curación gratis — excelente para pivots defensivos.",
    de: "Stellt 25% KP bei Treffer durch Wasser wieder her. Immun gegen Wasser und gibt kostenlose Heilung — hervorragend für defensive Pivots.",
    it: "Ripristina il 25% degli HP quando colpito da Acqua. immune all'Acqua e dà cura gratis — eccellente per pivot difensivi.",
    ja: "水技を受けるとHPを25%回復。水技を無効化しつつ無料回復 — 防御ピボットに最適。",
    ko: "물 기술 맞으면 HP 25% 회복. 물 기술 무효화 + 무료 회복 — 방어 피벗에 최적.",
  },
  "volt-absorb": {
    en: "Restores 25% HP when hit by an Electric move. Immune to Electric and provides free healing — excellent for defensive pivots.",
    fr: "Rend 25% des PV quand touché par une capacité Électrik. Immunisé contre l'Électrik et offre des soins gratuits.",
    es: "Restaura 25% de HP al ser golpeado por Eléctrico. Inmune al Eléctrico y da curación gratis.",
    de: "Stellt 25% KP bei Treffer durch Elektro wieder her. Immun gegen Elektro und gibt kostenlose Heilung.",
    it: "Ripristina il 25% degli HP quando colpito da Elettro. immune all'Elettro e dà cura gratis.",
    ja: "電気技を受けるとHPを25%回復。電気技を無効化しつつ無料回復 — 防御ピボットに最適。",
    ko: "전기 기술 맞으면 HP 25% 회복. 전기 기술 무효화 + 무료 회복 — 방어 피벗에 최적.",
  },
  "dry-skin": {
    en: "Restores HP in rain, weakens in sun. Immune to Water damage and heals in rain — great synergy with rain teams.",
    fr: "Rend des PV sous la pluie, affaibli au soleil. Immunisé contre l'Eau et soigne sous la pluie — excellente synergie avec les équipes pluie.",
    es: "Restaura HP bajo lluvia, debilita bajo sol. Inmune al daño de Agua y cura bajo lluvia — gran sinergia con equipos de lluvia.",
    de: "Stellt KP im Regen wieder her, schwächt in der Sonne. Immun gegen Wasserschaden und heilt im Regen — großartige Synergie mit Regen-Teams.",
    it: "Ripristina HP sotto pioggia, indebolisce sotto sole. immune ai danni Acqua e cura sotto pioggia — grande sinergia con team pioggia.",
    ja: "雨の時にHP回復、晴れの時に弱化。水ダメージを無効化し雨で回復 — 雨パと相性抜群。",
    ko: "비 올 때 HP 회복, 맑을 때 약화. 물 데미지 무효화 + 비 올 때 회복 — 레인 파티와 궁합 최고.",
  },
  "thick-fat": {
    en: "Halves damage from Fire and Ice moves. Removes two common weaknesses — excellent defensive ability for many Pokémon.",
    fr: "Réduit de moitié les dégâts des capacités Feu et Glace. Élimine deux faiblesses courantes — excellent talent défensif.",
    es: "Reduce a la mitad el daño de Fuego y Hielo. Elimina dos debilidades comunes — excelente habilidad defensiva.",
    de: "Halbiert Schaden von Feuer und Eis. Beseitigt zwei häufige Schwächen — hervorragende defensive Fähigkeit.",
    it: "Dimezza i danni da Fuoco e Ghiaccio. Rimuove due debolezze comuni — eccellente abilità difensiva.",
    ja: "炎・氷タイプの技のダメージを半分にする。2つの一般的な弱点を消す — 優秀な防御特性。",
    ko: "불꽃·얼음 타입 기술 데미지 절반. 2가지 일반적인 약점 제거 — 우수한 방어 특성.",
  },
  "filter": {
    en: "Reduces super-effective damage by 25%. Provides additional bulk against type matchups — great for tanks.",
    fr: "Réduit les dégâts super efficaces de 25%. Offre une résistance supplémentaire contre les matchups de types — excellent pour les tanks.",
    es: "Reduce el daño super efectivo 25%. Proporciona bulk adicional contra matchups de tipos — genial para tanks.",
    de: "Reduziert superschädigenden Schaden um 25%. Bietet zusätzliche Bulk gegen Typ-Matchups — großartig für Tanks.",
    it: "Riduce i danni super efficaci del 25%. Fornisce bulk aggiuntivo contro i matchup di tipi — ottimo per i tank.",
    ja: "効果抜群のダメージを25%軽減。タイプマッチアップに対して追加の耐久 — タンクに最適。",
    ko: "효과抜群 데미지 25% 감소. 타입 매치업에 추가 내구력 — 탱크에 최적.",
  },
  "solid-rock": {
    en: "Reduces super-effective damage by 25%. Same as Filter — provides additional bulk against type matchups.",
    fr: "Réduit les dégâts super efficaces de 25%. Comme Filtre — offre une résistance supplémentaire contre les matchups de types.",
    es: "Reduce el daño super efectivo 25%. Igual que Filtro — proporciona bulk adicional contra matchups de tipos.",
    de: "Reduziert superschädigenden Schaden um 25%. Wie Filter — bietet zusätzliche Bulk gegen Typ-Matchups.",
    it: "Riduce i danni super efficaci del 25%. Come Filtro — fornisce bulk aggiuntivo contro i matchup di tipi.",
    ja: "効果抜群のダメージを25%軽減。フィルターと同じ — タイプマッチアップに対して追加の耐久。",
    ko: "효과抜群 데미지 25% 감소. 필터와 동일 — 타입 매치업에 추가 내구력.",
  },
  "prism-armor": {
    en: "Reduces super-effective damage by 25%. Same as Filter and Solid Rock — provides additional bulk against type matchups.",
    fr: "Réduit les dégâts super efficaces de 25%. Comme Filtre et Armurouillée — offre une résistance supplémentaire.",
    es: "Reduce el daño super efectivo 25%. Igual que Filtro y Roca Sólida — proporciona bulk adicional.",
    de: "Reduziert superschädigenden Schaden um 25%. Wie Filter und Steinhaupt — bietet zusätzliche Bulk.",
    it: "Riduce i danni super efficaci del 25%. Come Filtro e Solidroccia — fornisce bulk aggiuntivo.",
    ja: "効果抜群のダメージを25%軽減。フィルター・がんじょうと同じ — タイプマッチアップに対して追加の耐久。",
    ko: "효과抜群 데미지 25% 감소. 필터·암석과 동일 — 타입 매치업에 추가 내구력.",
  },
  "technician": {
    en: "Boosts moves with 60 base power or less by 50%. Excellent for Pokémon with access to low-power, high-utility moves like Bullet Punch.",
    fr: "Booste les capacités de 60 PS de base ou moins de 50%. Excellent pour les Pokémon avec des capacités faibles mais utiles comme Pisto-Poing.",
    es: "Potencia movimientos de 60 de poder base o menos 50%. Excelente para Pokémon con movimientos de bajo poder pero alta utilidad como Puño Bala.",
    de: "Steigert Attacken mit 60 Basisstärke oder weniger um 50%. Hervorragend für Pokémon mit schwachen aber nützlichen Attacken wie Patronenhieb.",
    it: "Potenzia le mosse con 60 di potenza base o meno del 50%. Ottimo per Pokémon con mosse di bassa potenza ma alta utilità come Pugnospine.",
    ja: "威力60以下の技が50%強化。バレットパンチなど低威力・高有用性技を持つポケモンに最適。",
    ko: "위력 60 이하 기술 50% 강화. 벌렛펀치 등 저위력·고효용 기술 포켓몬에 최적.",
  },
  "moxie": {
    en: "Raises Attack by 1 stage after each KO. Snowballs into a devastating sweeper — each KO makes the next one easier.",
    fr: "Augmente l'Attaque d'1 cran après chaque KO. S'emballe en un sweeper dévastateur — chaque KO rend le suivant plus facile.",
    es: "Aumenta el Ataque 1 nivel tras cada KO. Se convierte en un sweeper devastador — cada KO hace el siguiente más fácil.",
    de: "Erhöht den Angriff um 1 Stufe nach jedem KO. Schneeballeffekt zu einem verheerenden Sweeper — jedes KO macht das nächste einfacher.",
    it: "Aumenta l'Attacco di 1 livello dopo ogni KO. Si trasforma in un sweeper devastante — ogni KO rende il successivo più facile.",
    ja: "KOごとに攻撃が1段階上がる。KOを重ねるほど強くなるスノーボールエフェクト — 破壊的なエースに成長。",
    ko: "KO마다 공격 1단계 상승. KO를 거듭할수록 강해지는 스노볼 이펙트 — 파괴적인 에이스로 성장.",
  },
  "grim-neigh": {
    en: "Raises Special Attack by 1 stage after each KO. Same as Moxie but for Special Attack — turns into a devastating special sweeper.",
    fr: "Augmente l'Attaque Spéciale d'1 cran après chaque KO. Comme Moxie mais pour l'Attaque Spéciale — devient un sweeper spécial dévastateur.",
    es: "Aumenta el Ataque Especial 1 nivel tras cada KO. Igual que Moxie pero para Ataque Especial — se convierte en un sweeper especial devastador.",
    de: "Erhöht den Spezial-Angriff um 1 Stufe nach jedem KO. Wie Moxie aber für Spezial-Angriff — wird zu einem verheerenden Spezial-Sweeper.",
    it: "Aumenta l'Attacco Speciale di 1 livello dopo ogni KO. Come Moxie ma per Attacco Speciale — diventa un sweeper speciale devastante.",
    ja: "KOごとに特攻が1段階上がる。モクシーの特攻版 — 破壊的な特殊エースに成長。",
    ko: "KO마다 특공 1단계 상승. 긍시의 특공판 — 파괴적인 특수 에이스로 성장.",
  },
  "chilling-neigh": {
    en: "Raises Attack by 1 stage after each KO. Same as Moxie — turns into a devastating physical sweeper.",
    fr: "Augmente l'Attaque d'1 cran après chaque KO. Comme Moxie — devient un sweeper physique dévastateur.",
    es: "Aumenta el Ataque 1 nivel tras cada KO. Igual que Moxie — se convierte en un sweeper físico devastador.",
    de: "Erhöht den Angriff um 1 Stufe nach jedem KO. Wie Moxie — wird zu einem verheerenden physischen Sweeper.",
    it: "Aumenta l'Attacco di 1 livello dopo ogni KO. Come Moxie — diventa un sweeper fisico devastante.",
    ja: "KOごとに攻撃が1段階上がる。モクシーと同じ — 破壊的な物理エースに成長。",
    ko: "KO마다 공격 1단계 상승. 긍시와 동일 — 파괴적인 물리 에이스로 성장.",
  },
  "beast-boost": {
    en: "Raises the highest stat by 1 stage after each KO. Snowballs into an unstoppable force — each KO makes it stronger.",
    fr: "Augmente la stat la plus élevée d'1 cran après chaque KO. S'emballe en une force imparable — chaque KO le rend plus fort.",
    es: "Aumenta la stat más alta 1 nivel tras cada KO. Se convierte en una fuerza imparable — cada KO lo hace más fuerte.",
    de: "Erhöht die höchste Stat um 1 Stufe nach jedem KO. Schneeballeffekt zu einer unaufhaltsamen Kraft — jedes KO macht es stärker.",
    it: "Aumenta la stat più alta di 1 livello dopo ogni KO. Si trasforma in una forza inarrestabile — ogni KO lo rende più forte.",
    ja: "KOごとに最も高い能力が1段階上がる。KOを重ねるほど止まらなくなる — 各KOでさらに強く。",
    ko: "KO마다 가장 높은 능력 1단계 상승. KO를 거듭할수록 멈출 수 없음 — 각 KO마다 더 강해짐.",
  },
  "protean": {
    en: "Changes the user's type to match the move used. Provides STAB on every attack and can avoid weaknesses — incredible offensive utility.",
    fr: "Change le type du Pokémon pour correspondre à la capacité utilisée. Fournit le STAB sur chaque attaque et peut éviter les faiblesses — utilité offensive incroyable.",
    es: "Cambia el tipo del usuario al del movimiento usado. Proporciona STAB en cada ataque y puede evitar debilidades — utilidad ofensiva increíble.",
    de: "Ändert den Typ des Anwenders zur verwendeten Attacke. Bietet STAB bei jedem Angriff und kann Schwächen vermeiden — unglaubliche offensive Nutzung.",
    it: "Cambia il tipo dell'utente in quello della mossa usata. Fornisce STAB su ogni attacco e può evitare debolezze — incredibile utilità offensiva.",
    ja: "使った技のタイプに自身のタイプが変化する。全ての攻撃でタイプ一致を得られ、弱点も回避可能 — 信じられない攻撃的有用性。",
    ko: "사용한 기술의 타입으로 자신의 타입이 변화. 모든 공격에서 타입 일치 획득, 약점도 회피 가능 — 믿을 수 없는 공격적 효용.",
  },
  "libero": {
    en: "Changes the user's type to match the move used. Same as Protean — provides STAB on every attack and can avoid weaknesses.",
    fr: "Change le type du Pokémon pour correspondre à la capacité utilisée. Comme Protéine — fournit le STAB sur chaque attaque.",
    es: "Cambia el tipo del usuario al del movimiento usado. Igual que Protean — proporciona STAB en cada ataque.",
    de: "Ändert den Typ des Anwenders zur verwendeten Attacke. Wie Protean — bietet STAB bei jedem Angriff.",
    it: "Cambia il tipo dell'utente in quello della mossa usata. Come Protean — fornisce STAB su ogni attacco.",
    ja: "使った技のタイプに自身のタイプが変化する。リベロと同じ — 全ての攻撃でタイプ一致を得られる。",
    ko: "사용한 기술의 타입으로 자신의 타입이 변화. 리베로와 동일 — 모든 공격에서 타입 일치 획득.",
  },
  "tinted-lens": {
    en: "Doubles the damage of not-very-effective moves. Turns resisted hits into neutral damage — excellent for coverage moves.",
    fr: "Double les dégâts des capacités peu efficaces. Transforme les coups résistés en dégâts neutres — excellent pour les capacités de couverture.",
    es: "Duplica el daño de movimientos poco efectivos. Convierte golpes resistidos en daño neutral — excelente para movimientos de cobertura.",
    de: "Verdoppelt den Schaden von nicht sehr effektiven Attacken. Macht widerstandene Treffer zu neutralem Schaden — hervorragend für Coverage-Attacken.",
    it: "Raddoppia il danno delle mosse poco efficaci. Trasforma i colpi resistiti in danno neutrale — ottimo per le mosse di copertura.",
    ja: "効果今一の技のダメージを2倍にする。耐えられた攻撃を等倍ダメージに変換 — カバー技に最適。",
    ko: "효과가 별로인 기술 데미지 2배. 막힌 공격을 등배 데미지로 변환 — 커버 기술에 최적.",
  },
  "sheer-force": {
    en: "Boosts moves with secondary effects by 30% but removes the effects. Great for raw damage output on moves like Fire Punch or Thunderbolt.",
    fr: "Booste les capacités avec effets secondaires de 30% mais supprime les effets. Excellent pour les dégâts bruts sur des capacités comme Poing de Feu ou Tonnerre.",
    es: "Potencia movimientos con efectos secundarios 30% pero elimina los efectos. Gran daño bruto en movimientos como Puño Fuego o Rayo.",
    de: "Steigert Attacken mit Nebeneffekten um 30% aber entfernt die Effekte. Großartig für rohen Schaden bei Attacken wie Feuerschlag oder Donnerblitz.",
    it: "Potenzia le mosse con effetti secondari del 30% ma rimuove gli effetti. Ottimo per danno puro su mosse come Fuocopugno o Fulmine.",
    ja: "追加効果のある技の威力30%アップだが効果は消滅。炎パンチや10万ボルトなどの純粋なダメージ出力に最適。",
    ko: "추가 효과 있는 기술 위력 30% 상승 but 효과 소멸. 번개펀치나 10만볼트 등의 순수 데미지 출력에 최적.",
  },
  "mold-breaker": {
    en: "Moves ignore the target's ability. Bypasses Levitate, Sturdy, Multiscale, and other defensive abilities — excellent for breaking walls.",
    fr: "Les capacités ignorent le talent de la cible. Passe à travers Lévitation, Fermeté, Multiscale et autres talents défensifs — excellent pour casser les murs.",
    es: "Los movimientos ignoran la habilidad del objetivo. Atraviesa Levitación, Robusta, Multiescala y otras habilidades defensivas — excelente para romper walls.",
    de: "Attacken ignorieren die Fähigkeit des Ziels. Umgeht Schwebe, Robustheit, Multiscale und andere defensive Fähigkeiten — hervorragend zum Brechen von Walls.",
    it: "Le mosse ignorano l'abilità del bersaglio. Supera Levitazione, Vigore, Multiscale e altre abilità difensive — ottimo per rompere i wall.",
    ja: "技が相手の特性を無視する。浮遊、頑丈、マルチスケイルなどの防御特性を貫通 — 壁壊しに最適。",
    ko: "기술이 상대 특성을 무시. 부유·옹골참·멀티스케일 등 방어 특성 관통 — 벽 부수기에 최적.",
  },
  "turboblaze": {
    en: "Moves ignore the target's ability. Same as Mold Breaker — bypasses Levitate, Sturdy, Multiscale, and other defensive abilities.",
    fr: "Les capacités ignorent le talent de la cible. Comme Brise Moule — passe à travers Lévitation, Fermeté, Multiscale.",
    es: "Los movimientos ignoran la habilidad del objetivo. Igual que Rómpe Moldes — atraviesa Levitación, Robusta, Multiescala.",
    de: "Attacken ignorieren die Fähigkeit des Ziels. Wie Bruchrüstung — umgeht Schwebe, Robustheit, Multiscale.",
    it: "Le mosse ignorano l'abilità del bersaglio. Come Rompiforma — supera Levitazione, Vigore, Multiscale.",
    ja: "技が相手の特性を無視する。ブレイクレコードと同じ — 浮遊・頑丈・マルチスケイルを貫通。",
    ko: "기술이 상대 특성을 무시. 테라볼테이지와 동일 — 부유·옹골참·멀티스케일 관통.",
  },
  "teravolt": {
    en: "Moves ignore the target's ability. Same as Mold Breaker — bypasses Levitate, Sturdy, Multiscale, and other defensive abilities.",
    fr: "Les capacités ignorent le talent de la cible. Comme Brise Moule — passe à travers Lévitation, Fermeté, Multiscale.",
    es: "Los movimientos ignoran la habilidad del objetivo. Igual que Rómpe Moldes — atraviesa Levitación, Robusta, Multiescala.",
    de: "Attacken ignorieren die Fähigkeit des Ziels. Wie Bruchrüstung — umgeht Schwebe, Robustheit, Multiscale.",
    it: "Le mosse ignorano l'abilità del bersaglio. Come Rompiforma — supera Levitazione, Vigore, Multiscale.",
    ja: "技が相手の特性を無視する。ブレイクレコードと同じ — 浮遊・頑丈・マルチスケイルを貫通。",
    ko: "기술이 상대 특성을 무시. 테라볼테이지와 동일 — 부유·옹골참·멀티스케일 관통.",
  },
  "drought": {
    en: "Summons harsh sunlight for 5 turns. Boosts Fire moves by 50%, weakens Water moves — cornerstone of sun teams.",
    fr: "Invoque un soleil ardent pendant 5 tours. Booste les capacités Feu de 50%, affaiblit les capacités Eau — pierre angulaire des équipes soleil.",
    es: "Invoca sol intenso por 5 turnos. Potencia movimientos de Fuego 50%, debilita Agua — piedra angular de equipos de sol.",
    de: "Beschwört harshes Sonnenlicht für 5 Runden. Steigert Feuer-Attacken um 50%, schwächt Wasser — Grundpfeiler von Sonnen-Teams.",
    it: "Evoca sole intenso per 5 turni. Potenzia le mosse di Fuoco del 50%, indebolisce Acqua — pietra angolare dei team sole.",
    ja: "5ターンの晴天にする。炎技50%強化、水技弱化 — 晴れパの要。",
    ko: "5턴 맑은 날씨. 불꽃 기술 50% 강화, 물 기술 약화 — 맑은 파티의 핵심.",
  },
  drizzle: {
    en: "Summons rain for 5 turns. Boosts Water moves by 50%, weakens Fire moves — cornerstone of rain teams.",
    fr: "Invoque la pluie pendant 5 tours. Booste les capacités Eau de 50%, affaiblit les capacités Feu — pierre angulaire des équipes pluie.",
    es: "Invoca lluvia por 5 turnos. Potencia movimientos de Agua 50%, debilita Fuego — piedra angular de equipos de lluvia.",
    de: "Beschwört Regen für 5 Runden. Steigert Wasser-Attacken um 50%, schwächt Feuer — Grundpfeiler von Regen-Teams.",
    it: "Evoca pioggia per 5 turni. Potenzia le mosse di Acqua del 50%, indebolisce Fuoco — pietra angolare dei team pioggia.",
    ja: "5ターンの雨にする。水技50%強化、炎技弱化 — 雨パの要。",
    ko: "5턴 비. 물 기술 50% 강화, 불꽃 기술 약화 — 레인 파티의 핵심.",
  },
  sandstream: {
    en: "Summons a sandstorm for 5 turns. Boosts Special Defense of Rock-types by 50% and deals residual damage — cornerstone of sand teams.",
    fr: "Invoque une tempête de sable pendant 5 tours. Booste la Défense Spéciale des types Roche de 50% et inflige des dégâts résiduels.",
    es: "Invoca tormenta de arena por 5 turnos. Aumenta la Defensa Especial de tipos Roca 50% y da daño residual — clave de equipos de arena.",
    de: "Beschwört Sandsturm für 5 Runden. Erhöht die Spezial-Verteidigung von Gestein um 50% und fügt Restschaden zu — Grundpfeiler von Sand-Teams.",
    it: "Evoca tempesta di sabbia per 5 turni. Aumenta la Difesa Speciale dei tipi Roccia del 50% e infligge danno residuo — chiave dei team sabbia.",
    ja: "5ターンの砂嵐にする。岩タイプの特防50%上昇 + 継続ダメージ — 砂パの要。",
    ko: "5턴 모래바람. 바위 타입 특방 50% 상승 + 지속 데미지 — 샌드 파티의 핵심.",
  },
  snowwarning: {
    en: "Summons hail for 5 turns. Boosts Defense of Ice-types by 50% and deals residual damage — cornerstone of hail teams.",
    fr: "Invoque la grêle pendant 5 tours. Booste la Défense des types Glace de 50% et inflige des dégâts résiduels.",
    es: "Invoca granizo por 5 turnos. Aumenta la Defensa de tipos Hielo 50% y da daño residual — clave de equipos de granizo.",
    de: "Beschwört Hagel für 5 Runden. Erhöht die Verteidigung von Eis um 50% und fügt Restschaden zu — Grundpfeiler von Hagel-Teams.",
    it: "Evoca grandine per 5 turni. Aumenta la Difesa dei tipi Ghiaccio del 50% e infligge danno residuo — chiave dei team grandine.",
    ja: "5ターンの霰にする。氷タイプの防御50%上昇 + 継続ダメージ — 霰パの要。",
    ko: "5턴 눈보라. 얼음 타입 방어 50% 상승 + 지속 데미지 — 눈보라 파티의 핵심.",
  },
  "desolate-land": {
    en: "Summons extremely harsh sunlight that cannot be overridden. Permanently boosts Fire moves and nullifies Water — Primal Groudon's signature ability.",
    fr: "Invoque un soleil ardent extrême qui ne peut être annulé. Booste en permanence les capacités Feu et annule l'Eau — talent signature de Primal Groudon.",
    es: "Invoca sol extremo que no puede ser anulado. Potencia permanentemente Fuego y anula Agua — habilidad exclusiva de Groudon Primal.",
    de: "Beschwört extremes Sonnenlicht, das nicht überschrieben werden kann. Boostet permanent Feuer und negiert Wasser — Signature-Fähigkeit von Primal-Groudon.",
    it: "Evoca sole estremo che non può essere sovrascritto. Potenzia permanentemente Fuoco e annulla Acqua — abilità esclusiva di Groudon Primordiale.",
    ja: "上書き不可能な超晴天にする。炎技を恒常的に強化し水技を無効化 — プライマルグラードンの専用特性。",
    ko: "덮어씌울 수 없는 초맑은 날씨. 불꽃 기술 영구 강화 + 물 기술 무효화 — 프라이멀 그란돈 전용 특성.",
  },
  "primordial-sea": {
    en: "Summons heavy rain that cannot be overridden. Permanently boosts Water moves and nullifies Fire — Primal Kyogre's signature ability.",
    fr: "Invoque une pluie torrentielle qui ne peut être annulée. Booste en permanence les capacités Eau et annule le Feu — talent signature de Primal Kyogre.",
    es: "Invoca lluvia intensa que no puede ser anulada. Potencia permanentemente Agua y anula Fuego — habilidad exclusiva de Kyogre Primal.",
    de: "Beschwört heftigen Regen, der nicht überschrieben werden kann. Boostet permanent Wasser und negiert Feuer — Signature-Fähigkeit von Primal-Kyogre.",
    it: "Evoca pioggia intensa che non può essere sovrascritta. Potenzia permanentemente Acqua e annulla Fuoco — abilità esclusiva di Kyogre Primordiale.",
    ja: "上書き不可能な大雨にする。水技を恒常的に強化し炎技を無効化 — プライマルカイオーガの専用特性。",
    ko: "덮어씌울 수 없는 폭우. 물 기술 영구 강화 + 불꽃 기술 무효화 — 프라이멀 가이오가 전용 특성.",
  },
  "delta-stream": {
    en: "Summons strong winds that remove Flying-type weaknesses. Protects Flying-types from super-effective hits — Mega Rayquaza's signature ability.",
    fr: "Invoque des vents forts qui retirent les faiblesses du type Vol. Protège les types Vol des coups super efficaces — talent signature de Méga Rayquaza.",
    es: "Invoca vientos fuertes que eliminan debilidades de tipo Volador. Protege tipos Voladores de golpes super efectivos — habilidad exclusiva de Mega Rayquaza.",
    de: "Beschwört starke Winde, die Flug-Schwächen entfernen. Schützt Flug-Typen vor superschädigenden Treffern — Signature-Fähigkeit von Mega-Rayquaza.",
    it: "Evoca venti forti che rimuovono le debolezze di tipo Volante. Protegge i tipi Volante dai colpi super efficaci — abilità esclusiva di Mega Rayquaza.",
    ja: "飛行タイプの弱点を消す強風を起こす。飛行タイプを効果抜群から守る — メガレックウザの専用特性。",
    ko: "비행 타입 약점 제거하는 강풍. 비행 타입을 효과抜群에서 보호 — 메가 레쿠쟈 전용 특성.",
  },
  "aura-break": {
    en: "Reverses the effect of Aura abilities (Fairy Aura, Dark Aura) — weakens them instead of boosting. Counters Mega Diancie and Mega Yveltal.",
    fr: "Inverse l'effet des talents Aura (Aura Féérique, Aura Ténèbres) — les affaiblit au lieu de les booster. Contre Méga Diancie et Méga Yveltal.",
    es: "Invierte el efecto de habilidades Aura (Aura Feérica, Aura Oscura) — las debilita en lugar de potenciar. Counter de Mega Diancie y Mega Yveltal.",
    de: "Kehrt den Effekt von Aura-Fähigkeiten um (Feen-Aura, Dunkel-Aura) — schwächt sie statt sie zu boosten. Counter gegen Mega-Diancie und Mega-Yveltal.",
    it: "Inverte l'effetto delle abilità Aura (Aura Fatata, Aura Oscura) — le indebolisce invece di potenziarle. Counter di Mega Diancie e Mega Yveltal.",
    ja: "オーラ特性（フェアリーオーラ・ダークオーラ）の効果を逆転 — 強化ではなく弱化させる。メガディアンシー・メガイベルタル対策。",
    ko: "오라 특성(페어리 오라·다크 오라) 효과 반전 — 강화가 아닌 약화. 메가 디안시·메가 이벨타르 대책.",
  },
  "dark-aura": {
    en: "Boosts Dark-type moves for all Pokémon on the field by 33%. Amplifies Dark-type damage for both sides — use carefully.",
    fr: "Booste les capacités Ténèbres de tous les Pokémon sur le terrain de 33%. Amplifie les dégâts Ténèbres des deux côtés — à utiliser avec prudence.",
    es: "Potencia movimientos de tipo Siniestro 33% para todos los Pokémon en campo. Amplifica daño Siniestro para ambos lados — usar con cuidado.",
    de: "Steigert Unlicht-Attacken aller Pokémon auf dem Feld um 33%. Verstärkt Unlicht-Schaden für beide Seiten — vorsichtig einsetzen.",
    it: "Potenzia le mosse di tipo Buio del 33% per tutti i Pokémon in campo. Amplifica il danno Buio per entrambi i lati — usare con cautela.",
    ja: "場上の全ポケモンの悪タイプ技を33%強化。両者の悪ダメージを増幅 — 慎重に使用。",
    ko: "배터의 모든 포켓몬 악 타입 기술 33% 강화. 양측의 악 데미지 증폭 — 신중하게 사용.",
  },
  "fairy-aura": {
    en: "Boosts Fairy-type moves for all Pokémon on the field by 33%. Amplifies Fairy-type damage for both sides — use carefully.",
    fr: "Booste les capacités Fée de tous les Pokémon sur le terrain de 33%. Amplifie les dégâts Fée des deux côtés — à utiliser avec prudence.",
    es: "Potencia movimientos de tipo Hada 33% para todos los Pokémon en campo. Amplifica daño Hada para ambos lados — usar con cuidado.",
    de: "Steigert Feen-Attacken aller Pokémon auf dem Feld um 33%. Verstärkt Feen-Schaden für beide Seiten — vorsichtig einsetzen.",
    it: "Potenzia le mosse di tipo Folletto del 33% per tutti i Pokémon in campo. Amplifica il danno Folletto per entrambi i lati — usare con cautela.",
    ja: "場上の全ポケモンの妖精タイプ技を33%強化。両者の妖精ダメージを増幅 — 慎重に使用。",
    ko: "배터의 모든 포켓몬 페어리 타입 기술 33% 강화. 양측의 페어리 데미지 증폭 — 신중하게 사용.",
  },
  "contrary": {
    en: "Reverses stat changes — buffs become debuffs and vice versa. Turns opponent's Intimidate into an Attack boost — incredible utility.",
    fr: "Inverse les changements de stats — les buffs deviennent des debuffs et vice versa. Transforme l'Intimidation adverse en boost d'Attaque — utilité incroyable.",
    es: "Invierte cambios de stats — los buffs se vuelven debuffs y viceversa. Convierte la Intimidación rival en boost de Ataque — utilidad increíble.",
    de: "Kehrt Stat-Änderungen um — Buffs werden zu Debuffs und umgekehrt. Verwandelt gegnerische Bedrohung in einen Angriffs-Boost — unglaubliche Nutzung.",
    it: "Inverte i cambiamenti di stats — i buff diventano debuff e viceversa. Trasforma l'Intimidazione avversaria in boost di Attacco — incredibile utilità.",
    ja: "ランク補正を逆転 — 上昇が下降に、下降が上昇に。相手の威嚇を攻撃アップに変換 — 信じられない有用性。",
    ko: "랭크 보정 반전 — 상승이 하강으로, 하강이 상승으로. 상대의 위협을 공격 업으로 변환 — 믿을 수 없는 효용.",
  },
  "simple": {
    en: "Doubles the effect of stat changes. A +1 boost becomes +2, a -1 drop becomes -2 — makes setup and sweeping much more powerful.",
    fr: "Double l'effet des changements de stats. Un boost de +1 devient +2, une baisse de -1 devient -2 — rend le setup et le sweep beaucoup plus puissants.",
    es: "Duplica el efecto de cambios de stats. Un boost de +1 se vuelve +2, una caída de -1 se vuelve -2 — hace setup y sweep mucho más poderosos.",
    de: "Verdoppelt den Effekt von Stat-Änderungen. Ein +1-Boost wird zu +2, ein -1-Drop wird zu -2 — macht Setup und Sweeping viel mächtiger.",
    it: "Raddoppia l'effetto dei cambiamenti di stats. Un boost di +1 diventa +2, una caduta di -1 diventa -2 — rende setup e sweep molto più potenti.",
    ja: "ランク補正の効果を2倍にする。+1が+2に、-1が-2に — 積み技とスイープが大幅に強化。",
    ko: "랭크 보정 효과 2배. +1이 +2로, -1이 -2로 — 쌓기와 스위프가 크게 강화.",
  },
  "unnerve": {
    en: "Prevents opponents from eating Berries. Denies Sitrus, Lum, and other berry-based recovery — great against berry-reliant strategies.",
    fr: "Empêche les adversaires de manger des Baies. Nier Sitrus, Lum et autres récupérations basées sur les Baies — excellent contre les stratégies basées sur les Baies.",
    es: "Evita que los rivales coman Bayas. Niega Sitrus, Lum y otras recuperaciones basadas en Bayas — genial contra estrategias de Bayas.",
    de: "Verhindert, dass Gegner Beeren essen. Verweigert Sitrus, Lum und andere Beeren-basierte Heilung — großartig gegen Beeren-Strategien.",
    it: "Impedisce agli avversari di mangiare Bacche. Nega Sitrus, Lum e altre cure basate su Bacche — ottimo contro strategie basate su Bacche.",
    ja: "相手がきのみを食べられなくする。オボンのみ、ラムのみなどの回復を封じる — きのみ依存戦略に強い。",
    ko: "상대가 나무열매를 먹을 수 없게 함. 열매 회복 봉쇄 — 나무열매 의존 전략에 강함.",
  },
  "pressure": {
    en: "Doubles the PP cost of moves used against this Pokémon. Drains opponent's PP faster — excellent for stall and defensive strategies.",
    fr: "Double le coût en PP des capacités utilisées contre ce Pokémon. Draine les PP adverses plus vite — excellent pour les stratégies stall et défensives.",
    es: "Duplica el costo de PP de movimientos usados contra este Pokémon. Drena PP del rival más rápido — excelente para stall y estrategias defensivas.",
    de: "Verdoppelt die AP-Kosten von Attacken gegen dieses Pokémon. Zieht gegnerische AP schneller ab — hervorragend für Stall- und defensive Strategien.",
    it: "Raddoppia il costo PP delle mosse usate contro questo Pokémon. Drena PP del rivale più velocemente — ottimo per stall e strategie difensive.",
    ja: "このポケモンに使われた技のPP消費を2倍にする。相手のPPを素早く枯渇させる — 受け・防御戦略に最適。",
    ko: "이 포켓몬에게 사용된 기술의 PP 소모 2배. 상대의 PP를 빠르게 고갈 —受け·방어 전략에 최적.",
  },
  "iron-fist": {
    en: "Boosts punching moves by 20%. Enhances moves like Drain Punch, Thunder Punch, and Ice Punch — great for physical attackers with punch coverage.",
    fr: "Booste les capacités de poing de 20%. Améliore les capacités comme Drainage-Poing, Électro-Poing et Glace-Poing — excellent pour les attaquants physiques.",
    es: "Potencia movimientos de puño 20%. Mejora movimientos como Drenaje Puño, Puño Trueno y Puño Hielo — genial para atacantes físicos con cobertura de puños.",
    de: "Steigert Schlag-Attacken um 20%. Verbessert Patronenhieb, Donnerschlag und Eishieb — großartig für physische Angreifer mit Punch-Coverage.",
    it: "Potenzia le mosse di pugno del 20%. Migliora mosse come Assorbipugno, Tuonopugno e Gelopugno — ottimo per attaccanti fisici con copertura di pugni.",
    ja: "パンチ技の威力20%アップ。ドレインパンチ、かみなりパンチ、れいとうパンチなどを強化 — パンチカバレッジを持つ物理アタッカーに最適。",
    ko: "펀치 기술 위력 20% 상승. 흡혈펀치·10만볼트펀치·냉동펀치 등 강화 — 펀치 커버리지 물리 공격자에 최적.",
  },
  "reckless": {
    en: "Boosts recoil and crash moves by 20%. Enhances Double-Edge, Flare Blitz, and High Jump Kick — great for high-risk, high-reward strategies.",
    fr: "Booste les capacités de recoil et de crash de 20%. Améliore les capacités comme Bélier, Boutefeu et Pied Sauté — excellent pour les stratégies à haut risque.",
    es: "Potencia movimientos de recoil y crash 20%. Mejora movimientos como Doble Filo, Envite Ígneo y Patada Salta Alta — genial para estrategias de alto riesgo.",
    de: "Steigert Recoil- und Crash-Attacken um 20%. Verbessert Risikotackle, Flammenblitz und Hochsprung-Fußkick — großartig für High-Risk-Strategien.",
    it: "Potenzia le mosse di recoil e crash del 20%. Migliora mosse come Rischiatutto, Fuococarica e Calciobalto — ottimo per strategie ad alto rischio.",
    ja: "反動技・転倒技の威力20%アップ。すてみタックル・フレアドライブ・とびげりげりなどを強化 — ハイリスク・ハイリターン戦略に最適。",
    ko: "반동 기술·전도 기술 위력 20% 상승. 몸통박치기·플레어드라이브·날아차기 등 강화 — 하이리스크·하이리턴 전략에 최적.",
  },
  "sturdy": {
    en: "Prevents being OHKO'd from full HP. Guarantees survival at 1 HP — excellent for setting up or using Focus Sash strategies.",
    fr: "Empêche d'être KO en 1 coup à pleine PV. Garantit la survie à 1 PV — excellent pour se setup ou utiliser des stratégies Focus Sash.",
    es: "Evita ser OHKO'd desde HP completo. Garantiza supervivencia a 1 HP — excelente para setup o estrategias de Focus Sash.",
    de: "Verhindert OHKO von vollen KP. Garantiert Überleben bei 1 KP — hervorragend zum Setup oder für Fokusgurt-Strategien.",
    it: "Impedisce di essere OHKO'd da HP pieni. Garantisce sopravvivenza a 1 HP — ottimo per setup o strategie di Focus Sash.",
    ja: "満HP時に一撃で倒されない。HP1で生存を保証 — 積み技や気合いの襷戦略に最適。",
    ko: "풀HP 시 일격사 방지. HP1 생존 보장 — 쌓기 기술이나 기합의 띠 전략에 최적.",
  },
  "shadow-shield": {
    en: "Halves damage taken when at full HP. Same as Multiscale — provides incredible setup opportunity for Lunala.",
    fr: "Réduit de moitié les dégâts subis à pleine PV. Comme Multiécaille — offre des opportunités de setup incroyables pour Lunala.",
    es: "Reduce a la mitad el daño recibido a HP completo. Igual que Multiescala — ofrece increíbles oportunidades de setup para Lunala.",
    de: "Halbiert erlittenen Schaden bei vollen KP. Wie Multiscale — bietet unglaubliche Setup-Möglichkeiten für Lunala.",
    it: "Dimezza i danni subiti a HP pieni. Come Multiscale — offre incredibili opportunità di setup per Lunala.",
    ja: "満HP時に受けるダメージを半分にする。マルチスケイルと同じ — ルナアーラの圧倒的な積み技機会。",
    ko: "풀HP 시 받는 데미지 절반. 멀티스케일과 동일 — 루나아라의 압도적인 쌓기 기회.",
  },
  "wonder-guard": {
    en: "Only super-effective moves hit. Extremely restrictive but incredibly powerful — only non-super-effective moves can damage this Pokémon.",
    fr: "Seules les capacités super efficaces touchent. Extrêmement restrictif mais incroyablement puissant — seules les capacités super efficaces peuvent blesser ce Pokémon.",
    es: "Solo movimientos super efectivos golpean. Extremadamente restrictivo pero increíblemente poderoso — solo movimientos super efectivos pueden dañar este Pokémon.",
    de: "Nur superschädigende Attacken treffen. Extrem einschränkend aber unglaublich mächtig — nur superschädigende Attacken können dieses Pokémon verletzen.",
    it: "Solo le mosse super efficaci colpiscono. Estremamente restrittivo ma incredibilmente potente — solo le mosse super efficaci possono danneggiare questo Pokémon.",
    ja: "効果抜群の技のみが当たる。極めて制限されるが非常に強力 — 効果抜群の技のみがこのポケモンにダメージを与えられる。",
    ko: "효과抜群 기술만 명중. 극도로 제한적이지만 매우 강력 — 효과抜群 기술만 이 포켓몬에게 데미지를 줄 수 있음.",
  },
  "hydration": {
    en: "Heals status conditions in rain. Cures burn, paralysis, poison, and sleep during rain — excellent for rain teams.",
    fr: "Soigne les états de statut sous la pluie. Guérit brûlure, paralysie, poison et sommeil pendant la pluie — excellent pour les équipes pluie.",
    es: "Cura estados de condición bajo lluvia. Cura quemadura, parálisis, veneno y sueño durante la lluvia — excelente para equipos de lluvia.",
    de: "Heilt Statusbedingungen im Regen. Heilt Verbrennung, Paralyse, Vergiftung und Schlaf im Regen — hervorragend für Regen-Teams.",
    it: "Cura le condizioni di stato sotto pioggia. Cura bruciatura, paralisi, veleno e sonno durante la pioggia — ottimo per team pioggia.",
    ja: "雨の時に状態異常を回復。雨の中でやけど・まひ・どく・眠りを回復 — 雨パに最適。",
    ko: "비 올 때 상태이상 회복. 비 중에 화상·마비·독·수면 회복 — 레인 파티에 최적.",
  },
  "natural-cure": {
    en: "Heals status conditions on switch-out. Cures burn, paralysis, poison, and sleep when switching — excellent pivot ability.",
    fr: "Soigne les états de statut en quittant le combat. Guérit brûlure, paralysie, poison et sommeil en changeant — excellent talent de pivot.",
    es: "Cura estados de condición al cambiar. Cura quemadura, parálisis, veneno y sueño al cambiar — excelente habilidad de pivot.",
    de: "Heilt Statusbedingungen beim Wechsel. Heilt Verbrennung, Paralyse, Vergiftung und Schlaf beim Wechseln — hervorragende Pivot-Fähigkeit.",
    it: "Cura le condizioni di stato allo switch. Cura bruciatura, paralisi, veleno e sonno quando si cambia — ottima abilità pivot.",
    ja: "交代時に状態異常を回復。交代するやけど・まひ・どく・眠りを回復 — 優秀なピボット特性。",
    ko: "교대 시 상태이상 회복. 교대 시 화상·마비·독·수면 회복 — 우수한 피벗 특성.",
  },
  "healer": {
    en: "Has a 30% chance to cure an ally's status condition in doubles. Provides team support in double battles — great for doubles strategies.",
    fr: "A 30% de chance de soigner l'état de statut d'un allié en doubles. Fournit un support d'équipe en doubles — excellent pour les stratégies doubles.",
    es: "Tiene 30% de probabilidad de curar el estado de un aliado en dobles. Proporciona soporte de equipo en dobles — genial para estrategias de dobles.",
    de: "Hat 30% Chance, die Statusbedingung eines Allies in Doubles zu heilen. Bietet Team-Support in Doubles — großartig für Doubles-Strategien.",
    it: "Ha il 30% di probabilità di curare lo stato di un alleato in doppio. Fornisce supporto di squadra in doppio — ottimo per strategie doppio.",
    ja: "ダブルバトルで30%の確率で味方の状態異常を回復。ダブルでチームサポート — ダブル戦略に最適。",
    ko: "더블 배틀에서 30% 확률로 아군 상태이상 회복. 더블에서 팀 서포트 — 더블 전략에 최적.",
  },
  "serene-grace": {
    en: "Doubles the chance of secondary effects. Turns 30% flinch into 60%, 30% burn into 60% — excellent for moves like Air Slash and Iron Head.",
    fr: "Double la chance d'effets secondaires. Transforme 30% de peur en 60%, 30% de brûlure en 60% — excellent pour des capacités comme Lame d'Air et Tête de Fer.",
    es: "Duplica la probabilidad de efectos secundarios. Convierte 30% de retroceso en 60%, 30% de quemadura en 60% — excelente para movimientos como Cuchilla de Aire y Cabeza de Hierro.",
    de: "Verdoppelt die Chance auf Nebeneffekte. Macht 30% Zurückweichen zu 60%, 30% Verbrennung zu 60% — hervorragend für Attacken wie Luftstoß und Eisenschädel.",
    it: "Raddoppia la probabilità di effetti secondari. Trasforma 30% di ritrosia in 60%, 30% di bruciatura in 60% — ottimo per mosse come Eterelama e Ferrartigli.",
    ja: "追加効果の発生率2倍。30%の怯みを60%に、30%の火傷を60%に — エアスラッシュ・アイアンヘッドなどに最適。",
    ko: "추가 효과 발생률 2배. 30% 풀죽음을 60%로, 30% 화상을 60%로 — 에어슬래시·아이언헤드 등에 최적.",
  },
  "super-luck": {
    en: "Raises the critical-hit ratio by one stage. Combined with Focus Energy or high-crit moves, guarantees devastating critical hits.",
    fr: "Augmente le taux de coup critique d'un cran. Combiné avec Puissance Critique ou des capacités à haut taux de crit, garantit des coups critiques dévastateurs.",
    es: "Aumenta el ratio de golpe crítico un nivel. Combinado con Concentración o movimientos de alto crit, garantiza golpes críticos devastadores.",
    de: "Erhöht die Volltrefferquote um eine Stufe. Kombiniert mit Fokusenergie oder High-Crit-Attacken garantiert es verheerende Volltreffer.",
    it: "Aumenta il ratio di colpo critico di un livello. Combinato con Concentrazione o mosse ad alto crit, garantisce colpi critici devastanti.",
    ja: "急所ランク+1。きあいだめや急所率の高い技と組み合わせると壊滅的な急所攻撃を保証。",
    ko: "급소 랭크+1. 기합막대나 급소율 높은 기술과 조합하면 치명적인 급소 공격 보장.",
  },
  "merciless": {
    en: "Moves always critical hit poisoned targets. Combined with Toxic, every attack becomes a critical hit — devastating against poisoned foes.",
    fr: "Les capacités sont toujours critiques sur les cibles empoisonnées. Combiné avec Toxic, chaque attaque devient un coup critique — dévastateur contre les ennemis empoisonnés.",
    es: "Los movimientos siempre son críticos contra objetivos envenenados. Combinado con Tóxico, cada ataque se vuelve crítico — devastador contra enemigos envenenados.",
    de: "Attacken sind immer Volltreffer gegen vergiftete Ziele. Kombiniert mit Toxin wird jeder Angriff zum Volltreffer — verheerend gegen vergiftete Gegner.",
    it: "Le mosse sono sempre critiche contro bersagli avvelenati. Combinato con Tossina, ogni attacco diventa critico — devastante contro nemici avvelenati.",
    ja: "毒状態の相手には必ず急所に当たる。どくどくと組み合わせると全ての攻撃が急所 — 毒状態の相手に壊滅的。",
    ko: "독 상태 상대에게는 항상 급소 명중. 맹독과 조합하면 모든 공격이 급소 — 독 상태 상대에게 치명적.",
  },
  "parental-bond": {
    en: "Attacks hit twice with 25% damage on the second hit. Effectively doubles damage output — incredible for physical attackers.",
    fr: "Les capacités touchent deux fois avec 25% de dégâts au second coup. Double efficacement les dégâts — incroyable pour les attaquants physiques.",
    es: "Los movimientos golpean dos veces con 25% de daño en el segundo golpe. Efectivamente duplica el daño — increíble para atacantes físicos.",
    de: "Attacken treffen zweimal mit 25% Schaden beim zweiten Treffer. Verdoppelt effektiv den Schaden — unglaublich für physische Angreifer.",
    it: "Le mosse colpiscono due volte con 25% di danno sul secondo colpo. Effettivamente raddoppia il danno — incredibile per attaccanti fisici.",
    ja: "技が2回当たり、2回目は25%ダメージ。実質的にダメージ2倍 — 物理アタッカーに信じられない性能。",
    ko: "기술이 2회 명중, 2회차는 25% 데미지. 실질적으로 데미지 2배 — 물리 공격자에 믿을 수 없는 성능.",
  },
  "compound-eyes": {
    en: "Increases accuracy by 30%. Makes inaccurate moves like Hurricane, Fire Blast, and Thunder much more reliable.",
    fr: "Augmente la précision de 30%. Rend les capacités imprécises comme Vent Violent, Déflagration et Tonnerre beaucoup plus fiables.",
    es: "Aumenta la precisión 30%. Hace movimientos imprecisos como Vendaval, Llamarada y Rayo mucho más confiables.",
    de: "Erhöht die Genauigkeit um 30%. Macht ungenaue Attacken wie Orkan, Flammenwurf und Donner viel zuverlässiger.",
    it: "Aumenta la precisione del 30%. Rende mosse imprecise come Uragano, Fuocobomba e Fulmine molto più affidabili.",
    ja: "命中率30%アップ。暴風・大文字・10万ボルトなどの不安定な技を大幅に安定化。",
    ko: "명중률 30% 상승. 폭풍·대문자·10만볼트 등 불안정한 기술을 크게 안정화.",
  },
  "no-guard": {
    en: "All moves hit both the user and the target. Makes 100% accuracy moves guaranteed to hit — great for moves like Dynamic Punch.",
    fr: "Toutes les capacités touchent l'utilisateur et la cible. Garantit que les capacités à 100% de précision touchent — excellent pour des capacités comme Dynamopoing.",
    es: "Todos los movimientos golpean al usuario y al objetivo. Garantiza que movimientos de 100% de precisión golpeen — genial para movimientos como Puño Dinámico.",
    de: "Alle Attacken treffen sowohl Anwender als auch Ziel. Garantiert, dass 100%-genaue Attacken treffen — großartig für Attacken wie Dynamithieb.",
    it: "Tutte le mosse colpiscono sia l'utente che il bersaglio. Garantisce che mosse al 100% di precisione colpiscano — ottimo per mosse come Dinamipugno.",
    ja: "全ての技が相手と自分に必ず当たる。命中100%の技が確実に命中 — ダイナミックパンチなどに最適。",
    ko: "모든 기술이 상대와 자신에게 반드시 명중. 명중 100% 기술이 확실히 명중 — 다이나믹펀치 등에 최적.",
  },
  "victory-star": {
    en: "Increases accuracy of all moves for the user's team by 10%. Provides team-wide accuracy boost — great for doubles strategies.",
    fr: "Augmente la précision de toutes les capacités de l'équipe de 10%. Fournit un boost de précision pour toute l'équipe — excellent pour les stratégies doubles.",
    es: "Aumenta la precisión de todos los movimientos del equipo 10%. Proporciona boost de precisión para todo el equipo — genial para estrategias de dobles.",
    de: "Erhöht die Genauigkeit aller Team-Attacken um 10%. Bietet teamweiten Genauigkeits-Boost — großartig für Doubles-Strategien.",
    it: "Aumenta la precisione di tutte le mosse del team del 10%. Fornisce boost di precisione per tutto il team — ottimo per strategie doppio.",
    ja: "味方全体の技の命中率10%アップ。チーム全体の命中率ブースト — ダブル戦略に最適。",
    ko: "아군 전체 기술 명중률 10% 상승. 팀 전체 명중률 부스트 — 더블 전략에 최적.",
  },
  "mummy": {
    en: "Changes the attacker's ability to Mummy on contact. Disrupts opponent's ability strategy — excellent against ability-reliant Pokémon.",
    fr: "Change le talent de l'attaquant en Momie au contact. Perturbe la stratégie de talent adverse — excellent contre les Pokémon dépendants de leurs talents.",
    es: "Cambia la habilidad del atacante a Momia al contacto. Interrumpe la estrategia de habilidad del rival — excelente contra Pokémon dependientes de habilidades.",
    de: "Ändert die Fähigkeit des Angreifers zu Mumie bei Kontakt. Stört gegnerische Fähigkeit-Strategie — hervorragend gegen fähigkeitsabhängige Pokémon.",
    it: "Cambia l'abilità dell'attaccante in Mummia al contatto. Interrompe la strategia di abilità del rivale — ottimo contro Pokémon dipendenti da abilità.",
    ja: "接触技で相手の特性をミイラに変化。相手の特性戦略を妨害 — 特性依存ポケモンに強い。",
    ko: "접촉 기술로 상대 특성을 미라로 변화. 상대 특성 전략 방해 — 특성 의존 포켓몬에 강함.",
  },
  "receiver": {
    en: "Copies an ally's ability when they faint. Inherits useful abilities like Regenerator or Levitate — great for doubles strategies.",
    fr: "Copie le talent d'un allié quand il est KO. Hérite de talents utiles comme Régé-Force ou Lévitation — excellent pour les stratégies doubles.",
    es: "Copia la habilidad de un aliado cuando se desmaya. Hereda habilidades útiles como Regeneración o Levitación — genial para estrategias de dobles.",
    de: "Kopiert die Fähigkeit eines Allies wenn er besiegt wird. Erbt nützliche Fähigkeiten wie Regenerator oder Schwebe — großartig für Doubles-Strategien.",
    it: "Copia l'abilità di un alleato quando sviene. Eredita abilità utili come Rigenerazione o Levitazione — ottimo per strategie doppio.",
    ja: "味方が倒れた時に特性をコピー。再生力・浮遊などの有用な特性を継承 — ダブル戦略に最適。",
    ko: "아군이 쓰러졌을 때 특성 복사. 재생력·부유 등 유용한 특성 상속 — 더블 전략에 최적.",
  },
  "power-construct": {
    en: "Transforms into Complete Forme when HP drops below 50%. Dramatically increases stats and changes typing — Zygarde's signature ability.",
    fr: "Se transforme en Forme Complète quand les PV tombent sous 50%. Augmente dramatiquement les stats et change le type — talent signature de Zygarde.",
    es: "Se transforma en Forma Completa cuando HP baja de 50%. Aumenta dramáticamente stats y cambia tipo — habilidad exclusiva de Zygarde.",
    de: "Verwandelt sich in die Komplette Form wenn KP unter 50% fallen. Erhöht dramatisch Stats und ändert Typ — Signature-Fähigkeit von Zygarde.",
    it: "Si trasforma in Forma Completa quando HP scende sotto 50%. Aumenta drammaticamente stats e cambia tipo — abilità esclusiva di Zygarde.",
    ja: "HP50%以下で完全体に変化。能力が大幅に上昇しタイプも変化 — ジガルデの専用特性。",
    ko: "HP 50% 이하 시 완전체로 변화. 능력이 크게 상승하고 타입도 변화 — 지가르데 전용 특성.",
  },
  "schooling": {
    en: "Transforms between Solo and School Forme at level 20+. School Forme has drastically higher stats but reverts when HP drops below 25%.",
    fr: "Se transforme entre la Forme Solo et la Forme Banc au niveau 20+. La Forme Banc a des stats considérablement plus élevées mais revient quand les PV tombent sous 25%.",
    es: "Se transforma entre Forma Solo y Forma Banco al nivel 20+. Forma Banco tiene stats drásticamente más altos pero vuelve cuando HP baja de 25%.",
    de: "Verwandelt sich zwischen Solo- und Schwarm-Form ab Level 20+. Schwarm-Form hat drastisch höhere Stats aber wechselt zurück wenn KP unter 25% fallen.",
    it: "Si trasforma tra Forma Solitaria e Forma Banco al livello 20+. Forma Banco ha stats drasticamente più alti ma torna quando HP scende sotto 25%.",
    ja: "レベル20以上で単独・群れ形態に変化。群れ形態は能力が大幅に高いがHP25%以下で元に戻る。",
    ko: "레벨 20 이상 시 단독·군집 형태로 변화. 군집 형태는 능력이 크게 높지만 HP 25% 이하 시 원래대로.",
  },
  "disguise": {
    en: "Blocks the first hit completely. Guarantees one free turn — excellent for setting up or using a powerful move.",
    fr: "Bloque le premier coup complètement. Garantit un tour gratuit — excellent pour se setup ou utiliser une capacité puissante.",
    es: "Bloquea el primer golpe completamente. Garantiza un turno gratis — excelente para setup o usar un movimiento poderoso.",
    de: "Blockiert den ersten Treffer komplett. Garantiert eine freie Runde — hervorragend zum Setup oder für eine mächtige Attacke.",
    it: "Blocca il primo colpo completamente. Garantisce un turno gratis — ottimo per setup o usare una mossa potente.",
    ja: "最初の攻撃を完全に防ぐ。1ターンの自由を保証 — 積み技や強力な技を使うのに最適。",
    ko: "첫 공격을 완전히 방어. 1턴의 자유 보장 — 쌓기 기술이나 강력한 기술 사용에 최적.",
  },
  "battle-bond": {
    en: "Transforms into Ash-Greninja after KOing an opponent. Ash-Greninja has boosted stats and Water Shuriken becomes a powerful multi-hit move.",
    fr: "Se transforme en Sachaninja après avoir KO un adversaire. Sachaninja a des stats boostées et Shuriken d'Eau devient une capacité multi-coups puissante.",
    es: "Se transforma en Ash-Greninja tras KO a un rival. Ash-Greninja tiene stats boosteados y Shuriken de Agua se vuelve un movimiento multi-golpe poderoso.",
    de: "Verwandelt sich in Ash-Greninja nach KO eines Gegners. Ash-Greninja hat geboostete Stats und Wasser-Shuriken wird zu einer mächtigen Multi-Hit-Attacke.",
    it: "Si trasforma in Ash-Greninja dopo KO di un avversario. Ash-Greninja ha stats boostati e Shuriken d'Acqua diventa una mossa multi-colpo potente.",
    ja: "相手を倒した後サトシゲッコウガに変化。能力が上昇し、みずしゅりけんが強力な連続技になる。",
    ko: "상대를 쓰러뜨린 후 지우게코우가 변화. 능력 상승 + 물수리검이 강력한 연속기로.",
  },
  "flower-gift": {
    en: "Boosts Attack and Special Defense of the user and ally by 50% in harsh sunlight. Excellent for sun teams in doubles.",
    fr: "Booste l'Attaque et la Défense Spéciale de l'utilisateur et de l'allié de 50% au soleil ardent. Excellent pour les équipes soleil en doubles.",
    es: "Potencia Ataque y Defensa Especial del usuario y aliado 50% bajo sol intenso. Excelente para equipos de sol en dobles.",
    de: "Steigert Angriff und Spezial-Verteidigung des Anwenders und Allies um 50% in harshem Sonnenlicht. Hervorragend für Sonnen-Teams in Doubles.",
    it: "Potenzia Attacco e Difesa Speciale dell'utente e alleato del 50% sotto sole intenso. Ottimo per team sole in doppio.",
    ja: "晴天時に自分と味方の攻撃・特防50%アップ。晴れパのダブルに最適。",
    ko: "맑은 날씨 시 자신과 아군 공격·특방 50% 상승. 맑은 파티 더블에 최적.",
  },
  "minus": {
    en: "Boosts Special Attack by 50% when a Minus or Plus ally is on the field. Provides team synergy in doubles — pair with Plus for maximum effect.",
    fr: "Booste l'Attaque Spéciale de 50% quand un allié Minus ou Plus est sur le terrain. Fournit une synergie d'équipe en doubles — associer avec Plus pour un effet maximum.",
    es: "Potencia Ataque Especial 50% cuando un aliado Minus o Plus está en campo. Proporciona sinergia de equipo en dobles — combinar con Plus para máximo efecto.",
    de: "Steigert Spezial-Angriff um 50% wenn ein Minus- oder Plus-Ally auf dem Feld ist. Bietet Team-Synergie in Doubles — mit Plus kombinieren für maximalen Effekt.",
    it: "Potenzia Attacco Speciale del 50% quando un alleato Minus o Plus è in campo. Fornisce sinergia di squadra in doppio — combinare con Plus per massimo effetto.",
    ja: "マイナス・プラスの味方が場にいる時特攻50%アップ。ダブルのチームシナジー — プラスと組んで最大効果。",
    ko: "마이너스·플러스 아군이 배터에 있을 때 특공 50% 상승. 더블 팀 시너지 — 플러스와 조합해 최대 효과.",
  },
  plus: {
    en: "Boosts Special Attack by 50% when a Minus or Plus ally is on the field. Provides team synergy in doubles — pair with Minus for maximum effect.",
    fr: "Booste l'Attaque Spéciale de 50% quand un allié Minus ou Plus est sur le terrain. Fournit une synergie d'équipe en doubles — associer avec Minus pour un effet maximum.",
    es: "Potencia Ataque Especial 50% cuando un aliado Minus o Plus está en campo. Proporciona sinergia de equipo en dobles — combinar con Minus para máximo efecto.",
    de: "Steigert Spezial-Angriff um 50% wenn ein Minus- oder Plus-Ally auf dem Feld ist. Bietet Team-Synergie in Doubles — mit Minus kombinieren für maximalen Effekt.",
    it: "Potenzia Attacco Speciale del 50% quando un alleato Minus o Plus è in campo. Fornisce sinergia di squadra in doppio — combinare con Minus per massimo effetto.",
    ja: "マイナス・プラスの味方が場にいる時特攻50%アップ。ダブルのチームシナジー — マイナスと組んで最大効果。",
    ko: "마이너스·플러스 아군이 배터에 있을 때 특공 50% 상승. 더블 팀 시너지 — 마이너스와 조합해 최대 효과.",
  },
  "flower-veil": {
    en: "Protects Grass-type allies from status conditions and stat drops. Provides team support for Grass-types in doubles — excellent for Grass teams.",
    fr: "Protège les alliés de type Plante des états de statut et des baisses de stats. Fournit un support d'équipe pour les types Plante en doubles — excellent pour les équipes Plante.",
    es: "Protege aliados de tipo Planta de estados de condición y caídas de stats. Proporciona soporte de equipo para tipos Planta en dobles — excelente para equipos de Planta.",
    de: "Schützt Pflanzen-Ally vor Statusbedingungen und Stat-Senkungen. Bietet Team-Support für Pflanzen-Typen in Doubles — hervorragend für Pflanzen-Teams.",
    it: "Protegge alleati di tipo Erba da condizioni di stato e cali di stats. Fornisce supporto di squadra per tipi Erba in doppio — ottimo per team Erba.",
    ja: "草タイプ味方を状態異常・能力低下から守る。ダブルの草タイプチームサポート — 草パに最適。",
    ko: "풀 타입 아군을 상태이상·능력 하락에서 보호. 더블 풀 타입 팀 서포트 — 풀 파티에 최적.",
  },
  "sweet-veil": {
    en: "Prevents the user and allies from falling asleep. Protects the team from sleep-inducing moves — great for doubles strategies.",
    fr: "Empêche l'utilisateur et les alliés de s'endormir. Protège l'équipe des capacités induisant le sommeil — excellent pour les stratégies doubles.",
    es: "Evita que el usuario y aliados se duerman. Protege al equipo de movimientos que inducen sueño — genial para estrategias de dobles.",
    de: "Verhindert, dass Anwender und Allies einschlafen. Schützt das Team vor schlafinduzierenden Attacken — großartig für Doubles-Strategien.",
    it: "Impedisce all'utente e alleati di addormentarsi. Protegge il team da mosse che inducono sonno — ottimo per strategie doppio.",
    ja: "自分と味方が眠らなくなる。眠り誘導技からチームを保護 — ダブル戦略に最適。",
    ko: "자신과 아군이 잠들지 않음. 수면 유도 기술로부터 팀 보호 — 더블 전략에 최적.",
  },
  "aroma-veil": {
    en: "Protects the user and allies from move-limiting effects. Blocks Taunt, Encore, Disable, and Torment — excellent support ability.",
    fr: "Protège l'utilisateur et les alliés des effets limitant les capacités. Bloque Provoc, Encore, Entrave et Tourmente — excellent talent de support.",
    es: "Protege al usuario y aliados de efectos que limitan movimientos. Bloquea Provocación, Encore, Anulación y Tormento — excelente habilidad de soporte.",
    de: "Schützt Anwender und Allies vor attackenlimitierenden Effekten. Blockiert Spotter, Zugabe, Aussetzer und Folterknecht — hervorragende Support-Fähigkeit.",
    it: "Protegge l'utente e alleati da effetti che limitano le mosse. Blocca Provocazione, Encore, Inibitore e Tormento — ottima abilità di supporto.",
    ja: "自分と味方を技制限効果から守る。挑発・アンコール・かなしばり・いちゃもんをブロック — 優秀なサポート特性。",
    ko: "자신과 아군을 기술 제한 효과로부터 보호. 도발·앵콜·잠그기·도발을 블록 — 우수한 서포트 특성.",
  },
  "friend-guard": {
    en: "Reduces damage taken by allies by 25%. Provides team-wide damage reduction in doubles — excellent for protecting fragile teammates.",
    fr: "Réduit les dégâts subis par les alliés de 25%. Fournit une réduction de dégâts pour toute l'équipe en doubles — excellent pour protéger les alliés fragiles.",
    es: "Reduce el daño recibido por aliados 25%. Proporciona reducción de daño para todo el equipo en dobles — excelente para proteger aliados frágiles.",
    de: "Reduziert erlittenen Schaden von Allies um 25%. Bietet teamweiten Schadensreduktion in Doubles — hervorragend zum Schutz zerbrechlicher Teammates.",
    it: "Riduce il danno subito dagli alleati del 25%. Fornisce riduzione di danno per tutto il team in doppio — ottimo per proteggere alleati fragili.",
    ja: "味方が受けるダメージ25%軽減。ダブルでチーム全体のダメージ軽減 — 脆い味方を守るのに最適。",
    ko: "아군이 받는 데미지 25% 감소. 더블에서 팀 전체 데미지 감소 — 약한 아군 보호에 최적.",
  },
  "sap-sipper": {
    en: "Immune to Grass-type moves and boosts Attack by 1 stage when hit. Turns opponent's Grass moves into free Attack boosts — great defensive ability.",
    fr: "Immunisé contre les capacités Plante et booste l'Attaque d'1 cran quand touché. Transforme les capacités Plante adverses en boosts d'Attaque gratuits — excellent talent défensif.",
    es: "Inmune a movimientos de tipo Planta y aumenta el Ataque 1 nivel al ser golpeado. Convierte movimientos de Planta rivales en boosts de Ataque gratis — gran habilidad defensiva.",
    de: "Immun gegen Pflanzen-Attacken und steigert den Angriff um 1 Stufe bei Treffer. Verwandelt gegnerische Pflanzen-Attacken in kostenlose Angriffs-Boosts — großartige defensive Fähigkeit.",
    it: "immune alle mosse di tipo Erba e aumenta l'Attacco di 1 livello quando colpito. Trasforma le mosse di Erba rivali in boost di Attacco gratis — grande abilità difensiva.",
    ja: "草タイプ技を無効化し、受けると攻撃1段階アップ。相手の草技を無料攻撃ブーストに変換 — 優秀な防御特性。",
    ko: "풀 타입 기술 무효 + 맞으면 공격 1단계 상승. 상대의 풀 기술을 무료 공격 부스트로 변환 — 우수한 방어 특성.",
  },
  "good-as-gold": {
    en: "Immune to all status moves. Cannot be affected by Taunt, Toxic, Will-O-Wisp, or any status move — incredible defensive utility.",
    fr: "Immunisé contre toutes les capacités de statut. Ne peut pas être affecté par Provoc, Toxic, Feu Follet ou toute capacité de statut — utilité défensive incroyable.",
    es: "Inmune a todos los movimientos de estado. No puede ser afectado por Provocación, Tóxico, Fuego Fatuo o cualquier movimiento de estado — utilidad defensiva increíble.",
    de: "Immun gegen alle Status-Attacken. Kann nicht von Spotter, Toxin, Irrlicht oder anderen Status-Attacken betroffen werden — unglaubliche defensive Nutzung.",
    it: "immune a tutte le mosse di stato. Non può essere influenzato da Provocazione, Tossina, Fuocofatuo o qualsiasi mossa di stato — incredibile utilità difensiva.",
    ja: "全ての変化技を無効化。挑発・どくどく・おにび・あらゆる変化技の影響を受けない — 信じられない防御的有用性。",
    ko: "모든 변화 기술 무효. 도발·맹독·도깨비불·어떤 변화 기술의 영향도 받지 않음 — 믿을 수 없는 방어적 효용.",
  },
  "tera-shift": {
    en: "Transforms into Terastal Form upon entering battle. Changes the Pokémon's typing and appearance — unique to Terapagos.",
    fr: "Se transforme en Forme Téracristal en entrant au combat. Change le type et l'apparence du Pokémon — unique à Terapagos.",
    es: "Se transforma en Forma Teracristal al entrar en batalla. Cambia el tipo y apariencia del Pokémon — exclusivo de Terapagos.",
    de: "Verwandelt sich in Terakristall-Form beim Betreten des Kampfes. Ändert den Typ und das Aussehen des Pokémon — einzigartig für Terapagos.",
    it: "Si trasforma in Forma Teracristallo entrando in battaglia. Cambia il tipo e l'aspetto del Pokémon — esclusivo di Terapagos.",
    ja: "出場時にテラスタルフォームに変化。ポケモンのタイプと外見が変化 — テラパゴスのみ。",
    ko: "출장 시 테라스탈 폼으로 변화. 포켓몬의 타입과 외형 변화 — 테라파고스 전용.",
  },
  "teraform-zero": {
    en: "Eliminates all weather and terrain effects upon entering battle. Resets the battlefield to neutral — great for countering weather teams.",
    fr: "Élimine tous les effets de météo et de terrain en entrant au combat. Réinitialise le champ de bataille à neutre — excellent pour contrer les équipes météo.",
    es: "Elimina todos los efectos de clima y terreno al entrar en batalla. Reinicia el campo de batalla a neutral — genial para counter equipos de clima.",
    de: "Beseitigt alle Wetter- und Gelände-Effekte beim Betreten des Kampfes. Setzt das Schlachtfeld auf neutral zurück — großartig zum Counter von Wetter-Teams.",
    it: "Elimina tutti gli effetti di meteo e terreno entrando in battaglia. Reimposta il campo di battaglia a neutrale — ottimo per counter team meteo.",
    ja: "出場時に全ての天気・フィールド効果を消去。戦場をニュートラルにリセット — 天候パ対策に最適。",
    ko: "출장 시 모든 날씨·필드 효과 제거. 전장을 뉴트럴로 리셋 — 날씨 파티 대책에 최적.",
  },
  "hospitality": {
    en: "Restores 25% HP to an ally when switching in. Provides team healing support in doubles — excellent for keeping teammates healthy.",
    fr: "Rend 25% des PV à un allié en entrant au combat. Fournit un support de guérison d'équipe en doubles — excellent pour garder les alliés en bonne santé.",
    es: "Restaura 25% de HP a un aliado al entrar en batalla. Proporciona soporte de curación de equipo en dobles — excelente para mantener aliados saludables.",
    de: "Stellt 25% KP eines Allies beim Wechsel wieder her. Bietet Team-Heilungssupport in Doubles — hervorragend um Teammates gesund zu halten.",
    it: "Ripristina il 25% degli HP di un alleato entrando in battaglia. Fornisce supporto di cura di squadra in doppio — ottimo per mantenere alleati sani.",
    ja: "出場時に味方のHPを25%回復。ダブルでチーム回復サポート — 味方を健康に保つのに最適。",
    ko: "출장 시 아군 HP 25% 회복. 더블에서 팀 회복 서포트 — 아군을 건강하게 유지에 최적.",
  },
  "supersweet-syrup": {
    en: "Lowers the opponent's evasion by 1 stage on switch-in. Provides immediate accuracy advantage — excellent for hitting reliably.",
    fr: "Baisse l'évasion de l'adversaire d'1 cran à l'entrée. Fournit un avantage de précision immédiat — excellent pour toucher de manière fiable.",
    es: "Reduce la evasión del rival 1 nivel al entrar. Proporciona ventaja de precisión inmediata — excelente para golpear confiablemente.",
    de: "Senkt die Ausweichrate des Gegners um 1 Stufe beim Wechsel. Bietet sofortigen Genauigkeitsvorteil — hervorragend für zuverlässiges Treffen.",
    it: "Abbassa l'evasione dell'avversario di 1 livello all'ingresso. Fornisce vantaggio di precisione immediato — ottimo per colpire in modo affidabile.",
    ja: "出場時に相手の回避率を1段階下げる。即座に命中率優位を提供 — 確実に当てるのに最適。",
    ko: "등장 시 상대의 회피율 1단계 하락. 즉시 명중률 우위 제공 — 확실히 맞추기에 최적.",
  },
  "mind-s-eyes": {
    en: "Moves cannot miss and ignore the target's evasion changes. Combined with high-power moves, guarantees hits regardless of evasion boosts.",
    fr: "Les capacités ne peuvent pas manquer et ignorent les changements d'évasion de la cible. Combiné avec des capacités puissantes, garantit des coups indépendamment des boosts d'évasion.",
    es: "Los movimientos no pueden fallar e ignoran los cambios de evasión del objetivo. Combinado con movimientos de alto poder, garantiza golpes independientemente de boosts de evasión.",
    de: "Attacken können nicht verfehlen und ignorieren Ausweichänderungen des Ziels. Kombiniert mit mächtigen Attacken garantiert es Treffer unabhängig von Ausweich-Boosts.",
    it: "Le mosse non possono mancare e ignorano i cambiamenti di evasione del bersaglio. Combinato con mosse potenti, garantisce colpi indipendentemente da boost di evasione.",
    ja: "技が外れず相手の回避率変化を無視する。強力な技と組み合わせると回避率アップに関係なく確実に命中。",
    ko: "기술이 빗나가지 않으며 상대의 회피율 변화 무시. 강력한 기술과 조합하면 회피율 업과 관계없이 확실히 명중.",
  },
  "zero-to-hero": {
    en: "Transforms into Hero Form when switched out. Hero Form has significantly higher stats — switch in and out to power up.",
    fr: "Se transforme en Forme Héros en quittant le combat. La Forme Héros a des stats significativement plus élevées — entrez et sortez pour vous renforcer.",
    es: "Se transforma en Forma Héroe al cambiar. Forma Héroe tiene stats significativamente más altos — entra y sale para potenciar.",
    de: "Verwandelt sich in Helden-Form beim Wechsel. Helden-Form hat deutlich höhere Stats — rein und raus wechseln zum Power-Up.",
    it: "Si trasforma in Forma Eroe allo switch. Forma Eroe ha stats significativamente più alti — entra ed esci per potenziare.",
    ja: "交代時にヒーローフォームに変化。ヒーローフォームは能力が大幅に高い — 出入りしてパワーアップ。",
    ko: "교대 시 히어로 폼으로 변화. 히어로 폼은 능력이 크게 높음 — 출입하여 파워업.",
  },
  "commander": {
    en: "Enters an ally's mouth when they use Dondozo's Order Up. Provides stat boosts and typing protection — unique doubles ability.",
    fr: "Entre dans la bouche d'un allié quand il utilise Ordre du Dondozo. Fournit des boosts de stats et une protection de type — talent de doubles unique.",
    es: "Entra en la boca de un aliado cuando usa Order Up de Dondozo. Proporciona boosts de stats y protección de tipo — habilidad única de dobles.",
    de: "Betrat den Mund eines Allies wenn es Dondozos Order Up verwendet. Bietet Stat-Boosts und Typ-Schutz — einzigartige Doubles-Fähigkeit.",
    it: "Entra nella bocca di un alleato quando usa Order Up di Dondozo. Fornisce boost di stats e protezione di tipo — abilità unica di doppio.",
    ja: "ドドゲザンのオーダーアップ使用時に味方の口に入る。能力ブーストとタイプ保護を提供 — 独特なダブル特性。",
    ko: "도도게잔의 오더 업 사용 시 아군의 입에 들어감. 능력 부스트와 타입 보호 제공 — 독특한 더블 특성.",
  },
  "costar": {
    en: "Copies an ally's stat changes when switching in. Inherits boosts from setup sweepers — excellent for doubles strategies.",
    fr: "Copie les changements de stats d'un allié en entrant au combat. Hérite des boosts des setup sweepers — excellent pour les stratégies doubles.",
    es: "Copia los cambios de stats de un aliado al entrar en batalla. Hereda boosts de setup sweepers — excelente para estrategias de dobles.",
    de: "Kopiert Stat-Änderungen eines Allies beim Wechsel. Erbt Boosts von Setup-Sweepers — hervorragend für Doubles-Strategien.",
    it: "Copia i cambiamenti di stats di un alleato entrando in battaglia. Eredita boost da setup sweeper — ottimo per strategie doppio.",
    ja: "出場時に味方のランク補正をコピー。積み技エースのブーストを継承 — ダブル戦略に最適。",
    ko: "출장 시 아군의 랭크 보정 복사. 쌓기 에이스의 부스트 상속 — 더블 전략에 최적.",
  },
  "supreme-overlord": {
    en: "Boosts Attack and Special Attack by 10% for each fainted ally. Gets stronger as teammates fall — devastating late-game sweeper.",
    fr: "Booste l'Attaque et l'Attaque Spéciale de 10% pour chaque allié KO. Devient plus fort à mesure que les alliés tombent — sweeper dévastateur en late-game.",
    es: "Potencia Ataque y Ataque Especial 10% por cada aliado KO. Se vuelve más fuerte a medida que caen compañeros — devastador sweeper de late-game.",
    de: "Steigert Angriff und Spezial-Angriff um 10% pro besiegten Ally. Wird stärker je mehr Teammates fallen — verheerender Late-Game-Sweeper.",
    it: "Potenzia Attacco e Attacco Speciale del 10% per ogni alleato KO. Diventa più forte man mano che i compagni cadono — devastante sweeper di late-game.",
    ja: "倒れた味方1体につき攻撃・特攻10%アップ。味方が倒れるほど強くなる — 終盤で壊滅的なスイーパー。",
    ko: "쓰러진 아군 1마리당 공격·특공 10% 상승. 아군이 쓰러질수록 강해짐 — 종반에 치명적인 스위퍼.",
  },
  "cud-chew": {
    en: "Re-eats a consumed Berry at the end of the next turn. Provides double the effect of a single Berry — excellent for recovery.",
    fr: "Remange une Baie consommée à la fin du tour suivant. Fournit le double de l'effet d'une seule Baie — excellent pour la récupération.",
    es: "Vuelve a comer una Baya consumida al final del siguiente turno. Proporciona el doble del efecto de una sola Baya — excelente para recuperación.",
    de: "Isst eine verbrauchte Beere am Ende der nächsten Runde erneut. Bietet doppelten Effekt einer einzelnen Beere — hervorragend für Erholung.",
    it: "Rimangia una Bacca consumata alla fine del turno successivo. Fornisce il doppio dell'effetto di una singola Bacca — ottimo per recupero.",
    ja: "次のターンの終わりに食べたきのみをもう一度食べる。1つのきのみ効果を2倍提供 — 回復に最適。",
    ko: "다음 턴 끝에 먹은 나무열매를 다시 먹음. 하나의 나무열매 효과 2배 제공 — 회복에 최적.",
  },
  "armortail": {
    en: "Prevents priority moves from hitting the user. Blocks Quick Attack, Sucker Punch, and other priority moves — excellent defensive ability.",
    fr: "Empêche les capacités prioritaires de toucher l'utilisateur. Bloque Vive-Attaque, Coup Bas et autres capacités prioritaires — excellent talent défensif.",
    es: "Evita que movimientos de prioridad golpeen al usuario. Bloquea Ataque Rápido, Golpe Bajo y otros movimientos de prioridad — excelente habilidad defensiva.",
    de: "Verhindert, dass Prioritäts-Attacken den Anwender treffen. Blockiert Ruckzuckhieb, Tiefschlag und andere Prioritäts-Attacken — hervorragende defensive Fähigkeit.",
    it: "Impedisce alle mosse di priorità di colpire l'utente. Blocca Attacco Rapido, Colpo Basso e altre mosse di priorità — ottima abilità difensiva.",
    ja: "優先度技からの攻撃を防ぐ。电光石火・不意打ちなどの優先度技をブロック — 優秀な防御特性。",
    ko: "우선도 기술로부터 공격 방지. 전광석화· 기습 등의 우선도 기술 블록 — 우수한 방어 특성.",
  },
  "well-baked-body": {
    en: "Boosts Defense by 1 stage when hit by a Fire move. Immune to Fire damage and provides free Defense boosts — great for physical walls.",
    fr: "Booste la Défense d'1 cran quand touché par une capacité Feu. Immunisé contre le Feu et offre des boosts de Défense gratuits — excellent pour les murs physiques.",
    es: "Aumenta la Defensa 1 nivel al ser golpeado por Fuego. Inmune al daño de Fuego y proporciona boosts de Defensa gratis — genial para walls físicos.",
    de: "Erhöht die Verteidigung um 1 Stufe bei Treffer durch Feuer. Immun gegen Feuerschaden und gibt kostenlose Verteidigungs-Boosts — großartig für physische Walls.",
    it: "Aumenta la Difesa di 1 livello quando colpito da Fuoco. immune ai danni di Fuoco e fornisce boost di Difesa gratis — ottimo per wall fisici.",
    ja: "炎技を受けると防御1段階アップ。炎ダメージを無効化しつつ無料防御ブースト — 物理壁に最適。",
    ko: "불꽃 기술 맞으면 방어 1단계 상승. 불꽃 데미지 무효화 + 무료 방어 부스트 — 물리 벽에 최적.",
  },
  "wind-rider": {
    en: "Boosts Attack by 1 stage when Tailwind is used. Immune to wind moves and provides free Attack boosts — excellent for Tailwind teams.",
    fr: "Booste l'Attaque d'1 cran quand Vent Arrière est utilisé. Immunisé contre les capacités de vent et offre des boosts d'Attaque gratuits — excellent pour les équipes Vent Arrière.",
    es: "Aumenta el Ataque 1 nivel cuando se usa Viento Favorable. Inmune a movimientos de viento y proporciona boosts de Ataque gratis — excelente para equipos de Viento Favorable.",
    de: "Erhöht den Angriff um 1 Stufe wenn Rückenwind verwendet wird. Immun gegen Wind-Attacken und gibt kostenlose Angriffs-Boosts — hervorragend für Rückenwind-Teams.",
    it: "Aumenta l'Attacco di 1 livello quando si usa Ventofavore. immune alle mosse di vento e fornisce boost di Attacco gratis — ottimo per team Ventofavore.",
    ja: "おいかぜ使用時に攻撃1段階アップ。風技を無効化しつつ無料攻撃ブースト — おいかぜパに最適。",
    ko: "뒷바람 사용 시 공격 1단계 상승. 바람 기술 무효화 + 무료 공격 부스트 — 뒷바람 파티에 최적.",
  },
  "guard-dog": {
    en: "Prevents being forced out by moves like Roar and Whirlwind. Boosts Attack when intimidated — excellent for staying in battle.",
    fr: "Empêche d'être forcé de sortir par des capacités comme Hurlement et Cyclone. Booste l'Attaque quand intimidé — excellent pour rester au combat.",
    es: "Evita ser forzado a salir por movimientos como Rugido y Remolino. Aumenta el Ataque cuando intimidado — excelente para permanecer en batalla.",
    de: "Verhindert, durch Attacken wie Brüller und Wirbelsturm hinausgeworfen zu werden. Steigert den Angriff bei Bedrohung — hervorragend um im Kampf zu bleiben.",
    it: "Impedisce di essere costretto ad uscire da mosse come Boato e Turbine. Aumenta l'Attacco quando intimidito — ottimo per rimanere in battaglia.",
    ja: "ほえる・ふきとばしなどで強制交代しない。威嚇時に攻撃アップ — 戦場に留まるのに最適。",
    ko: " 짖기·휘두르기 등으로 강제 교대 안 됨. 위협 시 공격 상승 — 전장에 머무르기에 최적.",
  },
  "rock-head": {
    en: "Reduces damage from super-effective moves by 25%. Same as Filter and Solid Rock — provides additional bulk against type matchups.",
    fr: "Réduit les dégâts des capacités super efficaces de 25%. Comme Filtre et Armurouillée — offre une résistance supplémentaire contre les matchups de types.",
    es: "Reduce el daño de movimientos super efectivos 25%. Igual que Filtro y Roca Sólida — proporciona bulk adicional contra matchups de tipos.",
    de: "Reduziert Schaden von superschädigenden Attacken um 25%. Wie Filter und Steinhaupt — bietet zusätzliche Bulk gegen Typ-Matchups.",
    it: "Riduce il danno da mosse super efficaci del 25%. Come Filtro e Solidroccia — fornisce bulk aggiuntivo contro i matchup di tipi.",
    ja: "効果抜群のダメージを25%軽減。フィルター・がんじょうと同じ — タイプマッチアップに対して追加の耐久。",
    ko: "효과抜群 데미지 25% 감소. 필터·암석과 동일 — 타입 매치업에 추가 내구력.",
  },
  "seed-sower": {
    en: "Sets Grassy Terrain when hit by an attack. Provides team-wide healing and boosts Grass moves — excellent for Grass teams.",
    fr: "Invoque le Champ Herbu quand touché par une attaque. Fournit des soins pour toute l'équipe et booste les capacités Plante — excellent pour les équipes Plante.",
    es: "Invoca Campo de Hierba al ser golpeado por un ataque. Proporciona curación para todo el equipo y potencia movimientos de Planta — excelente para equipos de Planta.",
    de: "Beschwört Grasfeld bei Treffer durch eine Attacke. Bietet teamweite Heilung und steigert Pflanzen-Attacken — hervorragend für Pflanzen-Teams.",
    it: "Evoca Campo Erboso quando colpito da un attacco. Fornisce cura per tutto il team e potenzia le mosse di Erba — ottimo per team Erba.",
    ja: "攻撃を受けるとグラスフィールドにする。チーム全体の回復と草技ブースト — 草パに最適。",
    ko: "공격 맞으면 글래스 필드 생성. 팀 전체 회복 + 풀 기술 부스트 — 풀 파티에 최적.",
  },
  "thermal-exchange": {
    en: "Boosts Attack when hit by a Fire move and prevents burn. Immune to burn and provides free Attack boosts — excellent for Fire matchups.",
    fr: "Booste l'Attaque quand touché par une capacité Feu et empêche la brûlure. Immunisé contre la brûlure et offre des boosts d'Attaque gratuits — excellent pour les matchups Feu.",
    es: "Aumenta el Ataque al ser golpeado por Fuego y previene quemadura. Inmune a quemadura y proporciona boosts de Ataque gratis — excelente para matchups de Fuego.",
    de: "Steigert den Angriff bei Treffer durch Feuer und verhindert Verbrennung. Immun gegen Verbrennung und gibt kostenlose Angriffs-Boosts — hervorragend für Feuer-Matchups.",
    it: "Aumenta l'Attacco quando colpito da Fuoco e previene bruciatura. immune a bruciatura e fornisce boost di Attacco gratis — ottimo per matchup di Fuoco.",
    ja: "炎技を受けると攻撃アップ + やけど防止。やけどを免疫しつつ無料攻撃ブースト — 炎マッチアップに最適。",
    ko: "불꽃 기술 맞으면 공격 상승 + 화상 방지. 화상 면역 + 무료 공격 부스트 — 불꽃 매치업에 최적.",
  },
  "anger-shell": {
    en: "Drops Defense and Special Defense but boosts Attack, Special Attack, and Speed when HP drops below 50%. High-risk, high-reward ability.",
    fr: "Baisse la Défense et la Défense Spéciale mais booste l'Attaque, l'Attaque Spéciale et la Vitesse quand les PV tombent sous 50%. Capacité à haut risque, haute récompense.",
    es: "Reduce Defensa y Defensa Especial pero aumenta Ataque, Ataque Especial y Velocidad cuando HP baja de 50%. Habilidad de alto riesgo, alta recompensa.",
    de: "Senkt Verteidigung und Spezial-Verteidigung aber steigert Angriff, Spezial-Angriff und Initiative wenn KP unter 50% fallen. High-Risk-High-Reward-Fähigkeit.",
    it: "Abbassa Difesa e Difesa Speciale ma aumenta Attacco, Attacco Speciale e Velocità quando HP scende sotto 50%. Abilità ad alto rischio, alta ricompensa.",
    ja: "HP50%以下で防御・特防が下がる代わりに攻撃・特攻・素早さが上がる。ハイリスク・ハイリターン特性。",
    ko: "HP 50% 이하 시 방어·특방 하락 대신 공격·특공·스피드 상승. 하이리스크·하이리턴 특성.",
  },
  "purifying-salt": {
    en: "Halves damage from Ghost-type moves and prevents status conditions. Immune to status and provides Ghost resistance — excellent defensive ability.",
    fr: "Réduit de moitié les dégâts des capacités Spectre et empêche les états de statut. Immunisé contre les états et offre une résistance Spectre — excellent talent défensif.",
    es: "Reduce a la mitad el daño de movimientos de tipo Fantasma y previene estados de condición. Inmune a estados y proporciona resistencia Fantasma — excelente habilidad defensiva.",
    de: "Halbiert Schaden von Geist-Attacken und verhindert Statusbedingungen. Immun gegen Status und bietet Geist-Resistenz — hervorragende defensive Fähigkeit.",
    it: "Dimezza il danno da mosse di tipo Spettro e previene condizioni di stato. immune a stati e fornisce resistenza Spettro — ottima abilità difensiva.",
    ja: "ゴースト技のダメージ半減 + 状態異常防止。状態異常を免疫しゴースト耐性提供 — 優秀な防御特性。",
    ko: "고스트 기술 데미지 절반 + 상태이상 방지. 상태이상 면역 + 고스트 내성 제공 — 우수한 방어 특성.",
  },
};
